const fs = require('fs');
const target = 'd:/NB PropKart/propertytech/lib/features/library/screens/service_agent_library_screen.dart';
const L = [];
L.push('');
L.push('  Widget _buildDocumentsTab(bool isDesktop, bool isTablet, bool isMobile) {');
L.push('    return SingleChildScrollView(padding: const EdgeInsets.all(CRMSpacing.m), child: Column(children: [');
L.push('      CRMCard(padding: const EdgeInsets.all(CRMSpacing.m), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [');
L.push('        Row(children: [');
L.push('          Icon(Icons.filter_alt_rounded, size: 18, color: CRMColors.primaryOf(context)),');
L.push('          const SizedBox(width: 6),');
L.push('          Text("Advanced Filters", style: CRMTypography.bodyMedium.copyWith(fontWeight: FontWeight.bold, color: CRMColors.textOf(context))),');
L.push('          const Spacer(),');
L.push('          TextButton(onPressed: _resetFilters, child: const Text("Reset All")),');
L.push('        ]),');
L.push('        const SizedBox(height: CRMSpacing.s),');
L.push('        LayoutBuilder(builder: (ctx, cons) {');
L.push('          int cols = isDesktop ? 3 : (isTablet ? 3 : 2);');
L.push('          double sp = CRMSpacing.s;');
L.push('          double w = ((cons.maxWidth - (sp * (cols - 1))) / cols) - 1.0;');
L.push('          return Wrap(spacing: sp, runSpacing: sp, children: [');
L.push('            SizedBox(width: w, child: TextField(');
L.push('              controller: _searchController, style: const TextStyle(fontSize: 13),');
L.push('              decoration: InputDecoration(hintText: "Search Agent or Document",');
L.push('                prefixIcon: const Icon(Icons.search_rounded, size: 18),');
L.push('                contentPadding: const EdgeInsets.symmetric(horizontal: 10, vertical: 10),');
L.push('                border: OutlineInputBorder(borderRadius: BorderRadius.circular(6))),');
L.push('              onChanged: (_) => _applyFiltersAndSort())),');
L.push('            _buildFilterDropdown("Service Type", _selectedServiceType, _serviceTypes, (val) { setState(() => _selectedServiceType = val!); _applyFiltersAndSort(); }, w),');
L.push('            _buildFilterDropdown("Doc Type", _selectedDocType, _dynamicDocTypes, (val) { setState(() => _selectedDocType = val!); _applyFiltersAndSort(); }, w),');
L.push('          ]);');
L.push('        }),');
L.push('      ])),');
L.push('      const SizedBox(height: CRMSpacing.m),');
L.push('      if (_filteredDocuments.isEmpty)');
L.push('        CRMEmptyState(title: "No Provider Documents", description: "No records match the current filters.", actionLabel: "Reset Filters", onActionPressed: _resetFilters)');
L.push('      else if (isMobile)');
L.push('        Column(children: [..._paginatedDocuments.map((doc) => _buildMobileDocumentCard(doc)), _buildMobilePagination()])');
L.push('      else');
L.push('        LayoutBuilder(builder: (ctx, cons) {');
L.push('          final sf = cons.maxWidth > 980 ? cons.maxWidth / 980 : 1.0;');
L.push('          return CRMDataTable<ServiceAgentDocument>(');
L.push('            currentPage: _currentPage, totalPages: _totalPages,');
L.push('            onPageChanged: (p) => setState(() => _currentPage = p),');
L.push('            totalItems: _filteredDocuments.length, itemsPerPage: _pageSize,');
L.push('            onItemsPerPageChanged: (r) { setState(() { _pageSize = r; _currentPage = 1; }); _applyFiltersAndSort(); },');
L.push('            sortField: _sortField, sortAscending: _sortAscending,');
L.push('            onSort: (f, asc) { setState(() { _sortField = f; _sortAscending = asc; }); _applyFiltersAndSort(); },');
L.push('            columns: [');
L.push('              CRMColumn<ServiceAgentDocument>(label: "Agent Name", sortable: true, sortField: "agentName", width: 140 * sf,');
L.push('                cellBuilder: (doc) => Text(doc.agentName, style: CRMTypography.bodyMedium.copyWith(fontWeight: FontWeight.bold, color: CRMColors.textOf(context)))),');
L.push('              CRMColumn<ServiceAgentDocument>(label: "Service Type", sortable: true, sortField: "serviceType", width: 110 * sf,');
L.push('                cellBuilder: (doc) => Text(doc.serviceType, style: TextStyle(color: CRMColors.textOf(context)))),');
L.push('              CRMColumn<ServiceAgentDocument>(label: "Mobile Number", width: 110 * sf,');
L.push('                cellBuilder: (doc) => Text(doc.mobileNumber, style: TextStyle(color: CRMColors.textOf(context)))),');
L.push('              CRMColumn<ServiceAgentDocument>(label: "Document Type", sortable: true, sortField: "documentType", width: 160 * sf,');
L.push('                cellBuilder: (doc) => Row(children: [');
L.push('                  FileIconHelper.getIconForExtension(doc.fileExtension),');
L.push('                  const SizedBox(width: 8),');
L.push('                  Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [');
L.push('                    Text(doc.documentType, style: CRMTypography.bodyMedium.copyWith(fontWeight: FontWeight.w600, color: CRMColors.textOf(context)), maxLines: 1, overflow: TextOverflow.ellipsis),');
L.push('                    Text(doc.fileSize, style: CRMTypography.caption.copyWith(color: CRMColors.textSecondaryOf(context))),');
L.push('                    TextButton(');
L.push('                      onPressed: () async { final url = doc.fileUrl; if (url != null && url.isNotEmpty) { final uri = Uri.parse(url); if (await canLaunchUrl(uri)) await launchUrl(uri, mode: LaunchMode.externalApplication); } },');
L.push('                      style: TextButton.styleFrom(padding: EdgeInsets.zero, minimumSize: const Size(0, 0), tapTargetSize: MaterialTapTargetSize.shrinkWrap),');
L.push('                      child: Text("View", style: TextStyle(color: CRMColors.primaryOf(context), fontSize: 12, fontWeight: FontWeight.bold))),');
L.push('                  ])),');
L.push('                ])),');
L.push('              CRMColumn<ServiceAgentDocument>(label: "Upload Date", sortable: true, sortField: "uploadDate", width: 100 * sf,');
L.push('                cellBuilder: (doc) => Text(DateFormat("dd MMM yyyy").format(doc.uploadDate), style: TextStyle(color: CRMColors.textOf(context)))),');
L.push('              CRMColumn<ServiceAgentDocument>(label: "Uploaded By", width: 100 * sf,');
L.push('                cellBuilder: (doc) => Text(doc.uploadedBy, style: TextStyle(color: CRMColors.textOf(context)))),');
L.push('              CRMColumn<ServiceAgentDocument>(label: "Actions", width: 60 * sf,');
L.push('                cellBuilder: (doc) => PopupMenuButton<String>(');
L.push('                  icon: Icon(Icons.more_vert_rounded, color: CRMColors.textSecondaryOf(context)),');
L.push('                  onSelected: (val) { switch (val) { case "view": _viewDocument(doc); break; case "edit": _showUploadEditDialog(doc); break; case "delete": _deleteDocument(doc); break; } },');
L.push('                  itemBuilder: (ctx) => [');
L.push('                    const PopupMenuItem(value: "view", child: Row(children: [Icon(Icons.visibility_outlined, size: 18), SizedBox(width: 8), Text("View")])),');
L.push('                    const PopupMenuItem(value: "edit", child: Row(children: [Icon(Icons.edit_outlined, size: 18), SizedBox(width: 8), Text("Edit")])),');
L.push('                    const PopupMenuDivider(),');
L.push('                    const PopupMenuItem(value: "delete", child: Row(children: [Icon(Icons.delete_outline_rounded, color: CRMColors.danger, size: 18), SizedBox(width: 8), Text("Delete", style: TextStyle(color: CRMColors.danger))])),');
L.push('                  ])),');
L.push('            ],');
L.push('            items: _paginatedDocuments,');
L.push('          );');
L.push('        }),');
L.push('    ]));');
L.push('  }');
L.push('');
L.push('  Widget _buildFilterDropdown(String label, String currentValue, List<String> items, void Function(String?) onChanged, double width) {');
L.push('    return SizedBox(width: width, child: DropdownButtonFormField<String>(');
L.push('      value: currentValue, isExpanded: true,');
L.push('      dropdownColor: CRMColors.cardBgOf(context),');
L.push('      decoration: InputDecoration(');
L.push('        labelText: label, labelStyle: CRMTypography.caption.copyWith(color: CRMColors.textSecondaryOf(context)),');
L.push('        contentPadding: const EdgeInsets.symmetric(horizontal: CRMSpacing.m, vertical: 10),');
L.push('        filled: true, fillColor: CRMColors.backgroundOf(context),');
L.push('        border: OutlineInputBorder(borderRadius: BorderRadius.circular(CRMBorderRadius.s), borderSide: BorderSide(color: CRMColors.borderOf(context).withOpacity(0.6))),');
L.push('        enabledBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(CRMBorderRadius.s), borderSide: BorderSide(color: CRMColors.borderOf(context).withOpacity(0.6))),');
L.push('        focusedBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(CRMBorderRadius.s), borderSide: BorderSide(color: CRMColors.primaryOf(context), width: 1.5)),');
L.push('      ),');
L.push('      style: CRMTypography.body.copyWith(color: CRMColors.textOf(context), fontSize: 13),');
L.push('      items: items.map((item) => DropdownMenuItem(value: item, child: Text(item, style: TextStyle(fontSize: 13, color: CRMColors.textOf(context)), overflow: TextOverflow.ellipsis))).toList(),');
L.push('      onChanged: onChanged));');
L.push('  }');
L.push('');
L.push('  Widget _buildMobileDocumentCard(ServiceAgentDocument doc) {');
L.push('    return Padding(padding: const EdgeInsets.only(bottom: CRMSpacing.m),');
L.push('      child: CRMCard(padding: const EdgeInsets.all(CRMSpacing.m),');
L.push('        child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [');
L.push('          Row(crossAxisAlignment: CrossAxisAlignment.start, children: [');
L.push('            FileIconHelper.getIconForExtension(doc.fileExtension, size: 24),');
L.push('            const SizedBox(width: CRMSpacing.s),');
L.push('            Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [');
L.push('              Text(doc.documentType, style: CRMTypography.bodyMedium.copyWith(fontWeight: FontWeight.bold, color: CRMColors.textOf(context)), maxLines: 2, overflow: TextOverflow.ellipsis),');
L.push('              Text("${doc.fileSize} - ${doc.agentName}", style: CRMTypography.caption.copyWith(color: CRMColors.textSecondaryOf(context))),');
L.push('            ])),');
L.push('            PopupMenuButton<String>(');
L.push('              icon: Icon(Icons.more_vert_rounded, color: CRMColors.textSecondaryOf(context)),');
L.push('              padding: EdgeInsets.zero, constraints: const BoxConstraints(),');
L.push('              onSelected: (val) { switch (val) { case "view": _viewDocument(doc); break; case "edit": _showUploadEditDialog(doc); break; case "delete": _deleteDocument(doc); break; } },');
L.push('              itemBuilder: (ctx) => [');
L.push('                const PopupMenuItem(value: "view", child: Row(children: [Icon(Icons.visibility_outlined, size: 18), SizedBox(width: 8), Text("View")])),');
L.push('                const PopupMenuItem(value: "edit", child: Row(children: [Icon(Icons.edit_outlined, size: 18), SizedBox(width: 8), Text("Edit")])),');
L.push('                const PopupMenuDivider(),');
L.push('                const PopupMenuItem(value: "delete", child: Row(children: [Icon(Icons.delete_outline_rounded, color: CRMColors.danger, size: 18), SizedBox(width: 8), Text("Delete", style: TextStyle(color: CRMColors.danger))])),');
L.push('              ]),');
L.push('          ]),');
L.push('          const SizedBox(height: CRMSpacing.m),');
L.push('          const Divider(height: 1),');
L.push('          const SizedBox(height: CRMSpacing.s),');
L.push('          _buildMobileDetailItem("Agent Name", doc.agentName),');
L.push('          _buildMobileDetailItem("Service Type", doc.serviceType),');
L.push('          _buildMobileDetailItem("Mobile Number", doc.mobileNumber),');
L.push('          _buildMobileDetailItem("Uploaded By", doc.uploadedBy),');
L.push('          _buildMobileDetailItem("Upload Date", DateFormat("dd MMM yyyy").format(doc.uploadDate)),');
L.push('          const SizedBox(height: CRMSpacing.m),');
L.push('          Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [');
L.push('            CRMStatusChip(status: doc.status.displayName),');
L.push('            Text(doc.fileExtension.toUpperCase(), style: CRMTypography.captionBold.copyWith(color: CRMColors.textMutedOf(context))),');
L.push('          ]),');
L.push('        ]),');
L.push('      ));');
L.push('  }');
L.push('');
L.push('  Widget _buildMobileDetailItem(String label, String value) {');
L.push('    return Padding(padding: const EdgeInsets.symmetric(vertical: 3.0),');
L.push('      child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [');
L.push('        Text(label, style: CRMTypography.caption.copyWith(color: CRMColors.textSecondaryOf(context))),');
L.push('        const SizedBox(width: CRMSpacing.m),');
L.push('        Expanded(child: Text(value, textAlign: TextAlign.end, style: CRMTypography.bodyMedium.copyWith(color: CRMColors.textOf(context), fontSize: 12.5, fontWeight: FontWeight.w500), overflow: TextOverflow.ellipsis)),');
L.push('      ]));');
L.push('  }');
L.push('');
L.push('  Widget _buildMobilePagination() {');
L.push('    if (_totalPages <= 1) return const SizedBox.shrink();');
L.push('    return Padding(padding: const EdgeInsets.only(top: CRMSpacing.s, bottom: CRMSpacing.l),');
L.push('      child: CRMCard(padding: const EdgeInsets.symmetric(horizontal: CRMSpacing.m, vertical: CRMSpacing.xs),');
L.push('        child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [');
L.push('          Text("Page $_currentPage of $_totalPages", style: CRMTypography.captionBold.copyWith(color: CRMColors.textSecondaryOf(context))),');
L.push('          Row(children: [');
L.push('            IconButton(icon: const Icon(Icons.chevron_left_rounded), onPressed: _currentPage > 1 ? () => setState(() => _currentPage--) : null),');
L.push('            IconButton(icon: const Icon(Icons.chevron_right_rounded), onPressed: _currentPage < _totalPages ? () => setState(() => _currentPage++) : null),');
L.push('          ]),');
L.push('        ])));');
L.push('  }');
L.push('}');
L.push('');
L.push('String generateUuidV4() {');
L.push('  final random = Random.secure();');
L.push('  final hexDigits = "0123456789abcdef";');
L.push('  final charCodes = List<int>.generate(36, (index) {');
L.push('    if (index == 8 || index == 13 || index == 18 || index == 23) return 45;');
L.push('    if (index == 14) return 52;');
L.push('    final digit = random.nextInt(16);');
L.push('    if (index == 19) return hexDigits.codeUnitAt((digit & 0x3) | 0x8);');
L.push('    return hexDigits.codeUnitAt(digit);');
L.push('  });');
L.push('  return String.fromCharCodes(charCodes);');
L.push('}');
fs.appendFileSync(target, L.join('\n'), 'utf8');
console.log('Part F OK - file complete');
const total = fs.readFileSync(target, 'utf8').split('\n').length;
console.log('Total lines:', total);
