const fs = require('fs');
const target = 'd:/NB PropKart/propertytech/lib/features/library/screens/service_agent_library_screen.dart';
const L = [];
L.push('');
L.push('  void _showAddAgentDialog([ServiceAgent? existing]) {');
L.push('    final isEditing = existing != null;');
L.push('    final formKey = GlobalKey<FormState>();');
L.push('    final nameCtrl = TextEditingController(text: existing?.agentName);');
L.push('    final mobileCtrl = TextEditingController(text: existing?.mobileNumber);');
L.push('    String localServiceType = existing?.serviceType ?? "Electrician";');
L.push('    DateTime? localDob = existing?.dateOfBirth;');
L.push('    String localImageUrl = existing?.agentImageUrl ?? "";');
L.push('    List<String> localAreas = List.from(existing?.areas ?? []);');
L.push('');
L.push('    showDialog(');
L.push('      context: context, barrierDismissible: false,');
L.push('      builder: (ctx) => StatefulBuilder(builder: (ctx, setModal) => Dialog(');
L.push('        backgroundColor: CRMColors.surfaceElevatedOf(context),');
L.push('        insetPadding: const EdgeInsets.symmetric(horizontal: 24, vertical: 24),');
L.push('        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(CRMBorderRadius.dialog)),');
L.push('        child: ConstrainedBox(constraints: const BoxConstraints(maxWidth: 560, maxHeight: 900),');
L.push('          child: Padding(padding: const EdgeInsets.all(CRMSpacing.l),');
L.push('            child: Form(key: formKey, child: SingleChildScrollView(child: Column(');
L.push('              mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start,');
L.push('              children: [');
L.push('                Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [');
L.push('                  Text(isEditing ? "Edit Agent" : "Add Service Agent",');
L.push('                    style: CRMTypography.sectionTitle.copyWith(color: CRMColors.textOf(context))),');
L.push('                  IconButton(icon: const Icon(Icons.close_rounded), onPressed: () => Navigator.pop(ctx)),');
L.push('                ]),');
L.push('                const SizedBox(height: CRMSpacing.m),');
L.push('                Center(child: AgentImageUploadWidget(');
L.push('                  initialImageUrl: localImageUrl.isNotEmpty ? localImageUrl : null,');
L.push('                  onImageUploaded: (url) => setModal(() => localImageUrl = url))),');
L.push('                const SizedBox(height: CRMSpacing.l),');
L.push('                CRMTextField(controller: nameCtrl, labelText: "Agent Name *", hintText: "e.g. Ramesh Kumar",');
L.push('                  validator: (v) => (v == null || v.trim().isEmpty) ? "Agent name required" : null),');
L.push('                const SizedBox(height: CRMSpacing.m),');
L.push('                Row(children: [');
L.push('                  Expanded(child: CRMTextField(controller: mobileCtrl, labelText: "Mobile Number *",');
L.push('                    hintText: "+91 XXXXX XXXXX", keyboardType: TextInputType.phone,');
L.push('                    validator: (v) => (v == null || v.trim().isEmpty) ? "Required" : null)),');
L.push('                  const SizedBox(width: CRMSpacing.m),');
L.push('                  Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [');
L.push('                    Text("Service Type *", style: CRMTypography.label.copyWith(color: CRMColors.textSecondaryOf(context))),');
L.push('                    const SizedBox(height: CRMSpacing.xs),');
L.push('                    DropdownButtonFormField<String>(');
L.push('                      value: localServiceType, isExpanded: true,');
L.push('                      dropdownColor: CRMColors.surfaceElevatedOf(context),');
L.push('                      decoration: InputDecoration(');
L.push('                        contentPadding: const EdgeInsets.symmetric(horizontal: CRMSpacing.m, vertical: CRMSpacing.s),');
L.push('                        filled: true, fillColor: CRMColors.cardBgOf(context),');
L.push('                        border: OutlineInputBorder(borderRadius: BorderRadius.circular(CRMBorderRadius.input),');
L.push('                          borderSide: BorderSide(color: CRMColors.borderOf(context)))),');
L.push('                      items: _serviceTypes.where((t) => t != "All").map((t) =>');
L.push('                        DropdownMenuItem(value: t, child: Text(t, style: TextStyle(color: CRMColors.textOf(context))))).toList(),');
L.push('                      onChanged: (v) { if (v != null) setModal(() => localServiceType = v); }),');
L.push('                  ])),');
L.push('                ]),');
L.push('                const SizedBox(height: CRMSpacing.m),');
L.push('                Column(crossAxisAlignment: CrossAxisAlignment.start, children: [');
L.push('                  Text("Date of Birth", style: CRMTypography.label.copyWith(color: CRMColors.textSecondaryOf(context))),');
L.push('                  const SizedBox(height: CRMSpacing.xs),');
L.push('                  InkWell(');
L.push('                    onTap: () async {');
L.push('                      final picked = await showDatePicker(context: context,');
L.push('                        initialDate: localDob ?? DateTime(1990), firstDate: DateTime(1940), lastDate: DateTime.now());');
L.push('                      if (picked != null) setModal(() => localDob = picked);');
L.push('                    },');
L.push('                    child: Container(');
L.push('                      padding: const EdgeInsets.symmetric(horizontal: CRMSpacing.m, vertical: 14),');
L.push('                      decoration: BoxDecoration(color: CRMColors.cardBgOf(context),');
L.push('                        borderRadius: BorderRadius.circular(CRMBorderRadius.input),');
L.push('                        border: Border.all(color: CRMColors.borderOf(context))),');
L.push('                      child: Row(children: [');
L.push('                        Icon(Icons.calendar_today_rounded, size: 16, color: CRMColors.textSecondaryOf(context)),');
L.push('                        const SizedBox(width: 8),');
L.push('                        Text(localDob != null ? DateFormat("dd MMM yyyy").format(localDob!) : "Select date of birth",');
L.push('                          style: CRMTypography.body.copyWith(');
L.push('                            color: localDob != null ? CRMColors.textOf(context) : CRMColors.textMutedOf(context))),');
L.push('                      ]),');
L.push('                    ),');
L.push('                  ),');
L.push('                  if (localDob != null)');
L.push('                    TextButton.icon(onPressed: () => setModal(() => localDob = null),');
L.push('                      icon: const Icon(Icons.clear_rounded, size: 14),');
L.push('                      label: const Text("Clear", style: TextStyle(fontSize: 12)),');
L.push('                      style: TextButton.styleFrom(padding: EdgeInsets.zero)),');
L.push('                ]),');
L.push('                const SizedBox(height: CRMSpacing.m),');
L.push('                AreaMultiSelectWidget(selectedAreas: localAreas, onChanged: (areas) => setModal(() => localAreas = areas)),');
L.push('                const SizedBox(height: CRMSpacing.l),');
L.push('                Row(mainAxisAlignment: MainAxisAlignment.end, children: [');
L.push('                  CRMButton(label: "Cancel", variant: CRMButtonVariant.outline, onPressed: () => Navigator.pop(ctx)),');
L.push('                  const SizedBox(width: CRMSpacing.s),');
L.push('                  CRMButton(');
L.push('                    label: isEditing ? "Save Changes" : (_isAdmin ? "Add Agent" : "Submit for Approval"),');
L.push('                    variant: CRMButtonVariant.primary,');
L.push('                    onPressed: () async {');
L.push('                      if (!formKey.currentState!.validate()) return;');
L.push('                      if (localAreas.isEmpty) {');
L.push('                        ScaffoldMessenger.of(context).showSnackBar(const SnackBar(');
L.push('                          content: Text("Please select at least one service area."),');
L.push('                          backgroundColor: CRMColors.danger)); return;');
L.push('                      }');
L.push('                      final approvalStatus = _isAdmin ? "approved" : "pending";');
L.push('                      final now = DateTime.now().toUtc().toIso8601String();');
L.push('                      try {');
L.push('                        if (isEditing) {');
L.push('                          await Supabase.instance.client.from("service_agents").update({');
L.push('                            "agent_name": nameCtrl.text.trim(), "mobile_number": mobileCtrl.text.trim(),');
L.push('                            "service_type": localServiceType,');
L.push('                            "date_of_birth": localDob?.toIso8601String().split("T").first,');
L.push('                            "agent_image_url": localImageUrl.isNotEmpty ? localImageUrl : null,');
L.push('                            "areas": localAreas, "updated_at": now,');
L.push('                          }).eq("id", existing.id);');
L.push('                        } else {');
L.push('                          await Supabase.instance.client.from("service_agents").insert({');
L.push('                            "id": generateUuidV4(), "agent_name": nameCtrl.text.trim(),');
L.push('                            "mobile_number": mobileCtrl.text.trim(), "service_type": localServiceType,');
L.push('                            "date_of_birth": localDob?.toIso8601String().split("T").first,');
L.push('                            "agent_image_url": localImageUrl.isNotEmpty ? localImageUrl : null,');
L.push('                            "areas": localAreas, "approval_status": approvalStatus,');
L.push('                            "added_by_user_id": _currentUserId, "added_by_name": _currentUserName,');
L.push('                            "created_at": now, "updated_at": now,');
L.push('                          });');
L.push('                        }');
L.push('                        if (!ctx.mounted) return;');
L.push('                        Navigator.pop(ctx);');
L.push('                        await _loadAgents();');
L.push('                        if (!mounted) return;');
L.push('                        ScaffoldMessenger.of(this.context).showSnackBar(SnackBar(');
L.push('                          content: Text(isEditing ? "Agent updated!" : (_isAdmin ? "Agent added!" : "Submitted for approval!")),');
L.push('                          backgroundColor: CRMColors.success, behavior: SnackBarBehavior.floating));');
L.push('                        if (!isEditing && !_isAdmin) _tabController.animateTo(1);');
L.push('                      } catch (e) {');
L.push('                        if (!ctx.mounted) return;');
L.push('                        ScaffoldMessenger.of(ctx).showSnackBar(SnackBar(content: Text("Save failed: $e"), backgroundColor: CRMColors.danger));');
L.push('                      }');
L.push('                    },');
L.push('                  ),');
L.push('                ]),');
L.push('              ],');
L.push('            ))),');
L.push('          ),');
L.push('        ),');
L.push('      )),');
L.push('    );');
L.push('  }');
fs.appendFileSync(target, L.join('\n'), 'utf8');
console.log('Part B OK');
