const fs = require('fs');
const target = 'd:/NB PropKart/propertytech/lib/features/library/screens/service_agent_library_screen.dart';
const L = [];
L.push('');
L.push('  void _showUploadEditDialog([ServiceAgentDocument? existingDoc]) {');
L.push('    final isEditing = existingDoc != null;');
L.push('    final formKey = GlobalKey<FormState>();');
L.push('    final agentCtrl = TextEditingController(text: existingDoc?.agentName);');
L.push('    final mobileCtrl = TextEditingController(text: existingDoc?.mobileNumber);');
L.push('    final descCtrl = TextEditingController(text: existingDoc?.description);');
L.push('    String localServiceType = existingDoc?.serviceType ?? "Electrician";');
L.push('    String localDocType = existingDoc?.documentType ?? "Aadhaar Card";');
L.push('    bool showCustomField = false;');
L.push('    final customDocCtrl = TextEditingController();');
L.push('    DocumentStatus localStatus = existingDoc?.status ?? DocumentStatus.active;');
L.push('    String localFileName = existingDoc?.documentName ?? "";');
L.push('    String localFileExt = existingDoc?.fileExtension ?? "pdf";');
L.push('    String localFileSize = existingDoc?.fileSize ?? "0 KB";');
L.push('    String localFileUrl = existingDoc?.fileUrl ?? "";');
L.push('    showDialog(');
L.push('      context: context, barrierDismissible: false,');
L.push('      builder: (context) => StatefulBuilder(builder: (context, setModalState) => Dialog(');
L.push('        backgroundColor: CRMColors.surfaceElevatedOf(context),');
L.push('        insetPadding: const EdgeInsets.symmetric(horizontal: 24, vertical: 24),');
L.push('        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(CRMBorderRadius.dialog)),');
L.push('        child: ConstrainedBox(constraints: const BoxConstraints(maxWidth: 550, maxHeight: 850),');
L.push('          child: Padding(padding: const EdgeInsets.all(CRMSpacing.l),');
L.push('            child: Form(key: formKey, child: SingleChildScrollView(child: Column(');
L.push('              mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [');
L.push('              Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [');
L.push('                Text(isEditing ? "Edit Agent Document" : "Upload Agent Document",');
L.push('                  style: CRMTypography.sectionTitle.copyWith(color: CRMColors.textOf(context))),');
L.push('                IconButton(icon: const Icon(Icons.close_rounded), onPressed: () => Navigator.pop(context)),');
L.push('              ]),');
L.push('              const SizedBox(height: CRMSpacing.m),');
L.push('              CRMTextField(controller: agentCtrl, labelText: "Agent Name *", hintText: "e.g. A1 Electricians Ltd",');
L.push('                validator: (val) => val == null || val.trim().isEmpty ? "Agent name required" : null),');
L.push('              const SizedBox(height: CRMSpacing.m),');
L.push('              Row(children: [');
L.push('                Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [');
L.push('                  Text("Service Type *", style: CRMTypography.label.copyWith(color: CRMColors.textSecondaryOf(context))),');
L.push('                  const SizedBox(height: CRMSpacing.xs),');
L.push('                  DropdownButtonFormField<String>(');
L.push('                    value: localServiceType, isExpanded: true,');
L.push('                    dropdownColor: CRMColors.surfaceElevatedOf(context),');
L.push('                    decoration: InputDecoration(contentPadding: const EdgeInsets.symmetric(horizontal: CRMSpacing.m, vertical: CRMSpacing.s),');
L.push('                      filled: true, fillColor: CRMColors.cardBgOf(context),');
L.push('                      border: OutlineInputBorder(borderRadius: BorderRadius.circular(CRMBorderRadius.input), borderSide: BorderSide(color: CRMColors.borderOf(context)))),');
L.push('                    items: _serviceTypes.where((t) => t != "All").map((t) =>');
L.push('                      DropdownMenuItem(value: t, child: Text(t, style: TextStyle(color: CRMColors.textOf(context))))).toList(),');
L.push('                    onChanged: (val) { if (val != null) setModalState(() => localServiceType = val); }),');
L.push('                ])),');
L.push('                const SizedBox(width: CRMSpacing.m),');
L.push('                Expanded(child: CRMTextField(controller: mobileCtrl, labelText: "Mobile Number *", hintText: "+91 XXXXX XXXXX",');
L.push('                  keyboardType: TextInputType.phone, validator: (val) => val == null || val.trim().isEmpty ? "Required" : null)),');
L.push('              ]),');
L.push('              const SizedBox(height: CRMSpacing.m),');
L.push('              Column(crossAxisAlignment: CrossAxisAlignment.start, children: [');
L.push('                Text("Document Type *", style: CRMTypography.label.copyWith(color: CRMColors.textSecondaryOf(context))),');
L.push('                const SizedBox(height: CRMSpacing.xs),');
L.push('                Row(children: [');
L.push('                  Expanded(child: DropdownButtonFormField<String>(');
L.push('                    value: ["Aadhaar Card", "Other"].contains(localDocType) ? localDocType : "Other",');
L.push('                    isExpanded: true, dropdownColor: CRMColors.surfaceElevatedOf(context),');
L.push('                    decoration: InputDecoration(contentPadding: const EdgeInsets.symmetric(horizontal: CRMSpacing.m, vertical: CRMSpacing.s),');
L.push('                      filled: true, fillColor: CRMColors.cardBgOf(context),');
L.push('                      border: OutlineInputBorder(borderRadius: BorderRadius.circular(CRMBorderRadius.input), borderSide: BorderSide(color: CRMColors.borderOf(context)))),');
L.push('                    items: ["Aadhaar Card", "Other"].map((t) =>');
L.push('                      DropdownMenuItem(value: t, child: Text(t, style: TextStyle(color: CRMColors.textOf(context))))).toList(),');
L.push('                    onChanged: (val) { if (val != null) setModalState(() { localDocType = val; showCustomField = val == "Other"; }); })),');
L.push('                  const SizedBox(width: CRMSpacing.s),');
L.push('                  IconButton(');
L.push('                    icon: Icon(showCustomField ? Icons.remove_circle_outline_rounded : Icons.add_circle_outline_rounded, color: CRMColors.primaryOf(context)),');
L.push('                    onPressed: () { setModalState(() { showCustomField = !showCustomField; localDocType = showCustomField ? "Other" : "Aadhaar Card"; }); }),');
L.push('                ]),');
L.push('                if (showCustomField) ...[');
L.push('                  const SizedBox(height: CRMSpacing.m),');
L.push('                  CRMTextField(controller: customDocCtrl, labelText: "Custom Document Type *", hintText: "e.g. GST Certificate",');
L.push('                    validator: (val) => val == null || val.trim().isEmpty ? "Required" : null),');
L.push('                ],');
L.push('              ]),');
L.push('              const SizedBox(height: CRMSpacing.m),');
L.push('              CRMTextField(controller: descCtrl, labelText: "Description", hintText: "Add description or notes...", maxLines: 2),');
L.push('              const SizedBox(height: CRMSpacing.m),');
L.push('              DragDropUploadZone(');
L.push('                initialFileName: localFileName, initialFileSize: localFileSize,');
L.push('                onOcrDetected: (name) => setModalState(() => agentCtrl.text = name),');
L.push('                onFileSelected: (name, ext, size, url) => setModalState(() { localFileName = name; localFileExt = ext; localFileSize = size; localFileUrl = url; }),');
L.push('              ),');
L.push('              const SizedBox(height: CRMSpacing.m),');
L.push('              Row(mainAxisAlignment: MainAxisAlignment.end, children: [');
L.push('                CRMButton(label: "Cancel", variant: CRMButtonVariant.outline, onPressed: () => Navigator.pop(context)),');
L.push('                const SizedBox(width: CRMSpacing.s),');
L.push('                CRMButton(');
L.push('                  label: isEditing ? "Save Changes" : "Upload",');
L.push('                  variant: CRMButtonVariant.primary,');
L.push('                  onPressed: () async {');
L.push('                    if (!formKey.currentState!.validate()) return;');
L.push('                    if (localFileName.isEmpty) { ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text("Please upload a document file."), backgroundColor: CRMColors.danger)); return; }');
L.push('                    if (localFileUrl.isEmpty || !localFileUrl.contains("res.cloudinary.com")) { ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text("Document must be uploaded to Cloudinary first."), backgroundColor: CRMColors.danger)); return; }');
L.push('                    final docType = showCustomField ? customDocCtrl.text.trim() : localDocType;');
L.push('                    String uploadedByName = "Admin";');
L.push('                    try {');
L.push('                      final cu = Supabase.instance.client.auth.currentUser;');
L.push('                      if (cu != null) {');
L.push('                        final p = await Supabase.instance.client.from("users").select("full_name, roles(name)").eq("id", cu.id).maybeSingle();');
L.push('                        if (p != null) { final r = p["roles"]?["name"]?.toString(); final n = p["full_name"]?.toString(); uploadedByName = r == "Admin" ? "Admin" : r == "Super Admin" ? "Super Admin" : (n ?? cu.email ?? "Admin"); }');
L.push('                      }');
L.push('                    } catch (_) {}');
L.push('                    try {');
L.push('                      if (isEditing) {');
L.push('                        await Supabase.instance.client.from("service_agent_documents").update({');
L.push('                          "agent_name": agentCtrl.text.trim(), "service_type": localServiceType,');
L.push('                          "mobile_number": mobileCtrl.text.trim(), "document_type": docType,');
L.push('                          "description": descCtrl.text.trim(), "status": localStatus.displayName.toLowerCase(),');
L.push('                          "file_size": localFileSize, "file_extension": localFileExt, "file_url": localFileUrl, "uploaded_by": uploadedByName,');
L.push('                        }).eq("id", existingDoc.id);');
L.push('                      } else {');
L.push('                        await Supabase.instance.client.from("service_agent_documents").insert({');
L.push('                          "id": generateUuidV4(), "agent_name": agentCtrl.text.trim(), "service_type": localServiceType,');
L.push('                          "mobile_number": mobileCtrl.text.trim(), "document_type": docType, "description": descCtrl.text.trim(),');
L.push('                          "status": localStatus.displayName.toLowerCase(), "file_size": localFileSize, "file_extension": localFileExt,');
L.push('                          "file_url": localFileUrl, "upload_date": DateTime.now().toUtc().toIso8601String(), "uploaded_by": uploadedByName,');
L.push('                        });');
L.push('                      }');
L.push('                      if (!context.mounted) return;');
L.push('                      Navigator.pop(context);');
L.push('                      await _loadDocumentsFromSupabase();');
L.push('                      if (!mounted) return;');
L.push('                      ScaffoldMessenger.of(this.context).showSnackBar(SnackBar(');
L.push('                        content: Text(isEditing ? "Document updated!" : "Document uploaded!"),');
L.push('                        backgroundColor: CRMColors.success, behavior: SnackBarBehavior.floating));');
L.push('                    } catch (err) {');
L.push('                      if (!context.mounted) return;');
L.push('                      ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text("Save failed: $err"), backgroundColor: CRMColors.danger));');
L.push('                    }');
L.push('                  },');
L.push('                ),');
L.push('              ]),');
L.push('            ])),');
L.push('          ),');
L.push('        ),');
L.push('      )),');
L.push('    );');
L.push('  }');
fs.appendFileSync(target, L.join('\n'), 'utf8');
console.log('Part D OK');
