const fs = require('fs');
const target = 'd:/NB PropKart/propertytech/lib/features/library/screens/service_agent_library_screen.dart';
const L = [];
L.push('');
L.push('  @override');
L.push('  Widget build(BuildContext context) {');
L.push('    final size = MediaQuery.of(context).size;');
L.push('    final isDesktop = size.width >= 1024;');
L.push('    final isTablet = size.width >= 600 && size.width < 1024;');
L.push('    final isMobile = size.width < 600;');
L.push('    return Scaffold(');
L.push('      backgroundColor: CRMColors.background,');
L.push('      body: SafeArea(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [');
L.push('        Padding(padding: const EdgeInsets.fromLTRB(CRMSpacing.m, CRMSpacing.m, CRMSpacing.m, 0),');
L.push('          child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [');
L.push('            Column(crossAxisAlignment: CrossAxisAlignment.start, children: [');
L.push('              const LibraryBreadcrumb(currentPageName: "Service Agent Library"),');
L.push('              Text("Service agents", style: CRMTypography.pageTitle.copyWith(color: CRMColors.textOf(context))),');
L.push('              Text("Store, filter, and organize service provider agreements and invoices.",');
L.push('                style: CRMTypography.caption.copyWith(color: CRMColors.textSecondaryOf(context))),');
L.push('            ]),');
L.push('            Row(children: [');
L.push('              PopupMenuButton<String>(');
L.push('                icon: Icon(Icons.download_rounded, color: CRMColors.primaryOf(context)),');
L.push('                tooltip: "Export Index",');
L.push('                onSelected: (val) => DocumentExportHelper.triggerExport(context, val),');
L.push('                itemBuilder: (context) => [');
L.push('                  const PopupMenuItem(value: "Excel", child: Text("Export to Excel")),');
L.push('                  const PopupMenuItem(value: "PDF", child: Text("Export to PDF")),');
L.push('                ],');
L.push('              ),');
L.push('              const SizedBox(width: CRMSpacing.s),');
L.push('              CRMButton(label: "Add agent", prefixIcon: Icons.add_rounded, onPressed: () => _showAddAgentDialog()),');
L.push('            ]),');
L.push('          ])),');
L.push('        const SizedBox(height: CRMSpacing.s),');
L.push('        Padding(padding: const EdgeInsets.symmetric(horizontal: CRMSpacing.m),');
L.push('          child: Wrap(spacing: CRMSpacing.m, children: [');
L.push('            SizedBox(width: isDesktop ? 220 : double.infinity,');
L.push('              child: CRMKPICard(title: "Total Approved Agents", value: "${_approvedAgents.length}",');
L.push('                icon: Icons.badge_rounded, iconColor: CRMColors.primaryOf(context), benefit: "Approved agents ready to work")),');
L.push('            if (_pendingAgents.isNotEmpty)');
L.push('              SizedBox(width: isDesktop ? 220 : double.infinity,');
L.push('                child: CRMKPICard(title: "Pending Approval", value: "${_pendingAgents.length}",');
L.push('                  icon: Icons.pending_actions_rounded, iconColor: Colors.orange, benefit: "Awaiting admin review")),');
L.push('          ])),');
L.push('        const SizedBox(height: CRMSpacing.m),');
L.push('        Padding(padding: const EdgeInsets.symmetric(horizontal: CRMSpacing.m),');
L.push('          child: TabBar(');
L.push('            controller: _tabController,');
L.push('            labelStyle: CRMTypography.bodyMedium.copyWith(fontWeight: FontWeight.w600),');
L.push('            unselectedLabelStyle: CRMTypography.body,');
L.push('            labelColor: CRMColors.primaryOf(context),');
L.push('            unselectedLabelColor: CRMColors.textSecondaryOf(context),');
L.push('            indicatorColor: CRMColors.primaryOf(context), indicatorWeight: 2.5,');
L.push('            tabs: [');
L.push('              const Tab(text: "Agents"),');
L.push('              Tab(child: Row(mainAxisSize: MainAxisSize.min, children: [');
L.push('                const Text("Pending"),');
L.push('                if (_pendingAgents.isNotEmpty) ...[');
L.push('                  const SizedBox(width: 6),');
L.push('                  Container(');
L.push('                    padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),');
L.push('                    decoration: BoxDecoration(color: Colors.orange, borderRadius: BorderRadius.circular(10)),');
L.push('                    child: Text("${_pendingAgents.length}", style: const TextStyle(color: Colors.white, fontSize: 10, fontWeight: FontWeight.bold)),');
L.push('                  ),');
L.push('                ],');
L.push('              ])),');
L.push('              const Tab(text: "Documents"),');
L.push('            ],');
L.push('          )),');
L.push('        Expanded(child: TabBarView(controller: _tabController, children: [');
L.push('          _buildApprovedAgentsTab(),');
L.push('          _buildPendingTab(),');
L.push('          _buildDocumentsTab(isDesktop, isTablet, isMobile),');
L.push('        ])),');
L.push('      ])),');
L.push('    );');
L.push('  }');
L.push('');
L.push('  Widget _buildApprovedAgentsTab() {');
L.push('    if (_agentsLoading) return const Center(child: CircularProgressIndicator());');
L.push('    if (_approvedAgents.isEmpty) return CRMEmptyState(title: "No Approved Agents",');
L.push('      description: "No agents approved yet.", actionLabel: "Add Agent", onActionPressed: () => _showAddAgentDialog());');
L.push('    return ListView.builder(padding: const EdgeInsets.all(CRMSpacing.m),');
L.push('      itemCount: _approvedAgents.length,');
L.push('      itemBuilder: (ctx, i) => _buildAgentCard(_approvedAgents[i], isPending: false));');
L.push('  }');
L.push('');
L.push('  Widget _buildPendingTab() {');
L.push('    if (_agentsLoading) return const Center(child: CircularProgressIndicator());');
L.push('    if (_pendingAgents.isEmpty) return const CRMEmptyState(title: "No Pending Agents",');
L.push('      description: "All agents reviewed. New submissions appear here.");');
L.push('    return ListView.builder(padding: const EdgeInsets.all(CRMSpacing.m),');
L.push('      itemCount: _pendingAgents.length,');
L.push('      itemBuilder: (ctx, i) => _buildAgentCard(_pendingAgents[i], isPending: true));');
L.push('  }');
L.push('');
L.push('  Widget _buildAgentCard(ServiceAgent agent, {required bool isPending}) {');
L.push('    return Padding(padding: const EdgeInsets.only(bottom: CRMSpacing.m),');
L.push('      child: CRMCard(padding: const EdgeInsets.all(CRMSpacing.m),');
L.push('        child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [');
L.push('          Row(children: [');
L.push('            Container(width: 52, height: 52,');
L.push('              decoration: BoxDecoration(shape: BoxShape.circle, color: CRMColors.cardBgOf(context),');
L.push('                border: Border.all(color: CRMColors.primaryOf(context).withOpacity(0.3), width: 2)),');
L.push('              clipBehavior: Clip.antiAlias,');
L.push('              child: agent.agentImageUrl != null && agent.agentImageUrl!.isNotEmpty');
L.push('                ? Image.network(agent.agentImageUrl!, fit: BoxFit.cover,');
L.push('                    errorBuilder: (_, __, ___) => Icon(Icons.person_rounded, size: 28, color: CRMColors.textMutedOf(context)))');
L.push('                : Icon(Icons.person_rounded, size: 28, color: CRMColors.textMutedOf(context)),');
L.push('            ),');
L.push('            const SizedBox(width: CRMSpacing.m),');
L.push('            Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [');
L.push('              Text(agent.agentName, style: CRMTypography.bodyMedium.copyWith(fontWeight: FontWeight.bold, color: CRMColors.textOf(context))),');
L.push('              const SizedBox(height: 2),');
L.push('              Row(children: [');
L.push('                Container(padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 2),');
L.push('                  decoration: BoxDecoration(color: CRMColors.primaryOf(context).withOpacity(0.1), borderRadius: BorderRadius.circular(12)),');
L.push('                  child: Text(agent.serviceType, style: TextStyle(fontSize: 11, color: CRMColors.primaryOf(context), fontWeight: FontWeight.w600))),');
L.push('                const SizedBox(width: 6),');
L.push('                Icon(Icons.phone_rounded, size: 12, color: CRMColors.textMutedOf(context)),');
L.push('                const SizedBox(width: 2),');
L.push('                Text(agent.mobileNumber, style: CRMTypography.caption.copyWith(color: CRMColors.textSecondaryOf(context))),');
L.push('              ]),');
L.push('            ])),');
L.push('            if (isPending && _isAdmin) ...[');
L.push('              IconButton(tooltip: "Approve", onPressed: () => _approveAgent(agent),');
L.push('                icon: Container(padding: const EdgeInsets.all(6),');
L.push('                  decoration: BoxDecoration(color: CRMColors.success.withOpacity(0.1), borderRadius: BorderRadius.circular(8)),');
L.push('                  child: const Icon(Icons.check_rounded, color: CRMColors.success, size: 18))),');
L.push('              IconButton(tooltip: "Reject", onPressed: () => _rejectAgent(agent),');
L.push('                icon: Container(padding: const EdgeInsets.all(6),');
L.push('                  decoration: BoxDecoration(color: CRMColors.danger.withOpacity(0.1), borderRadius: BorderRadius.circular(8)),');
L.push('                  child: const Icon(Icons.close_rounded, color: CRMColors.danger, size: 18))),');
L.push('            ] else if (!isPending) ...[');
L.push('              PopupMenuButton<String>(');
L.push('                icon: Icon(Icons.more_vert_rounded, color: CRMColors.textSecondaryOf(context)),');
L.push('                onSelected: (val) { if (val == "edit") _showAddAgentDialog(agent); if (val == "delete") _deleteAgent(agent); },');
L.push('                itemBuilder: (ctx) => [');
L.push('                  const PopupMenuItem(value: "edit", child: Row(children: [Icon(Icons.edit_outlined, size: 18), SizedBox(width: 8), Text("Edit")])),');
L.push('                  const PopupMenuDivider(),');
L.push('                  const PopupMenuItem(value: "delete", child: Row(children: [Icon(Icons.delete_outline_rounded, color: CRMColors.danger, size: 18), SizedBox(width: 8), Text("Delete", style: TextStyle(color: CRMColors.danger))])),');
L.push('                ]),');
L.push('            ],');
L.push('          ]),');
L.push('          if (agent.areas.isNotEmpty) ...[');
L.push('            const SizedBox(height: CRMSpacing.s),');
L.push('            const Divider(height: 1),');
L.push('            const SizedBox(height: CRMSpacing.s),');
L.push('            Row(crossAxisAlignment: CrossAxisAlignment.start, children: [');
L.push('              Icon(Icons.location_on_rounded, size: 14, color: CRMColors.textMutedOf(context)),');
L.push('              const SizedBox(width: 4),');
L.push('              Expanded(child: Wrap(spacing: 4, runSpacing: 4, children: agent.areas.map((a) => Container(');
L.push('                padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),');
L.push('                decoration: BoxDecoration(color: CRMColors.backgroundOf(context), borderRadius: BorderRadius.circular(6), border: Border.all(color: CRMColors.borderOf(context))),');
L.push('                child: Text(a, style: CRMTypography.caption.copyWith(color: CRMColors.textSecondaryOf(context))),');
L.push('              )).toList())),');
L.push('            ]),');
L.push('          ],');
L.push('          if (agent.dateOfBirth != null) ...[');
L.push('            const SizedBox(height: CRMSpacing.xs),');
L.push('            Row(children: [');
L.push('              Icon(Icons.cake_rounded, size: 13, color: CRMColors.textMutedOf(context)),');
L.push('              const SizedBox(width: 4),');
L.push('              Text("DOB: ${DateFormat("dd MMM yyyy").format(agent.dateOfBirth!)}", style: CRMTypography.caption.copyWith(color: CRMColors.textSecondaryOf(context))),');
L.push('            ]),');
L.push('          ],');
L.push('          if (isPending) ...[');
L.push('            const SizedBox(height: CRMSpacing.s),');
L.push('            Row(children: [');
L.push('              Icon(Icons.person_outline_rounded, size: 13, color: CRMColors.textMutedOf(context)),');
L.push('              const SizedBox(width: 4),');
L.push('              Text("Added by: ${agent.addedByName}", style: CRMTypography.caption.copyWith(color: CRMColors.textSecondaryOf(context))),');
L.push('              const SizedBox(width: 12),');
L.push('              Icon(Icons.access_time_rounded, size: 13, color: CRMColors.textMutedOf(context)),');
L.push('              const SizedBox(width: 4),');
L.push('              Text(DateFormat("dd MMM yyyy").format(agent.createdAt), style: CRMTypography.caption.copyWith(color: CRMColors.textSecondaryOf(context))),');
L.push('            ]),');
L.push('          ],');
L.push('        ]),');
L.push('      ));');
L.push('  }');
fs.appendFileSync(target, L.join('\n'), 'utf8');
console.log('Part E OK');
