const fs = require('fs');

const target = 'd:\\NB PropKart\\propertytech\\lib\\features\\library\\screens\\service_agent_library_screen.dart';

const L = [
`// PART 1 - Write these lines first using writeFileSync`,
`import 'package:flutter/material.dart';`,
`import 'package:intl/intl.dart';`,
`import 'dart:math';`,
`import 'package:url_launcher/url_launcher.dart';`,
`import 'package:supabase_flutter/supabase_flutter.dart';`,
`import '../../../core/design_system/tokens/app_colors.dart';`,
`import '../../../core/design_system/tokens/app_spacing.dart';`,
`import '../../../core/design_system/tokens/app_typography.dart';`,
`import '../../../core/design_system/widgets/buttons.dart';`,
`import '../../../core/design_system/widgets/cards.dart';`,
`import '../../../core/design_system/widgets/crm_data_table.dart';`,
`import '../../../core/design_system/widgets/crm_status_chips.dart';`,
`import '../../../core/design_system/widgets/dialogs.dart';`,
`import '../../../core/design_system/widgets/empty_state.dart';`,
`import '../../../core/design_system/widgets/inputs.dart';`,
`import '../models/document_model.dart';`,
`import 'library_widgets.dart';`,
`import 'agent_widgets.dart';`,
``,
`class ServiceAgentLibraryScreen extends StatefulWidget {`,
`  const ServiceAgentLibraryScreen({super.key});`,
`  @override`,
`  State<ServiceAgentLibraryScreen> createState() => _ServiceAgentLibraryScreenState();`,
`}`,
``,
`class _ServiceAgentLibraryScreenState extends State<ServiceAgentLibraryScreen>`,
`    with SingleTickerProviderStateMixin {`,
`  late TabController _tabController;`,
`  List<ServiceAgentDocument> _allDocuments = [];`,
`  List<ServiceAgentDocument> _filteredDocuments = [];`,
`  List<ServiceAgent> _approvedAgents = [];`,
`  List<ServiceAgent> _pendingAgents = [];`,
`  bool _agentsLoading = false;`,
`  String _currentUserRole = '';`,
`  String _currentUserName = '';`,
`  String? _currentUserId;`,
`  String? _sortField = 'uploadDate';`,
`  bool _sortAscending = false;`,
`  int _currentPage = 1;`,
`  int _pageSize = 10;`,
`  final TextEditingController _searchController = TextEditingController();`,
`  String _selectedServiceType = 'All';`,
`  String _selectedDocType = 'All';`,
`  bool _isLoading = false;`,
``,
`  final List<String> _serviceTypes = [`,
`    'All', 'Electrician', 'Plumber', 'Carpenter', 'Painter',`,
`    'AC Technician', 'Cleaning Service', 'Pest Control', 'CCTV Service',`,
`    'Interior Designer', 'Movers & Packers', 'Other'`,
`  ];`,
``,
`  List<String> get _dynamicDocTypes {`,
`    final types = _allDocuments.map((d) => d.documentType).toSet().toList();`,
`    if (!types.contains('Aadhaar Card')) types.insert(0, 'Aadhaar Card');`,
`    types.sort((a, b) { if (a == 'Aadhaar Card') return -1; if (b == 'Aadhaar Card') return 1; return a.compareTo(b); });`,
`    return ['All', ...types];`,
`  }`,
``,
`  bool get _isAdmin => _currentUserRole == 'Admin' || _currentUserRole == 'Super Admin';`,
``,
`  @override`,
`  void initState() {`,
`    super.initState();`,
`    _tabController = TabController(length: 3, vsync: this);`,
`    _fetchCurrentUser();`,
`    _loadDocumentsFromSupabase();`,
`    _loadAgents();`,
`  }`,
``,
`  @override`,
`  void dispose() {`,
`    _tabController.dispose();`,
`    _searchController.dispose();`,
`    super.dispose();`,
`  }`,
``,
`  Future<void> _fetchCurrentUser() async {`,
`    try {`,
`      final user = Supabase.instance.client.auth.currentUser;`,
`      if (user == null) return;`,
`      _currentUserId = user.id;`,
`      final profile = await Supabase.instance.client`,
`          .from('users').select('full_name, roles(name)').eq('id', user.id).maybeSingle();`,
`      if (profile != null && mounted) {`,
`        setState(() {`,
`          _currentUserRole = profile['roles']?['name']?.toString() ?? '';`,
`          _currentUserName = profile['full_name']?.toString() ?? user.email?.split('@').first ?? '';`,
`        });`,
`      }`,
`    } catch (e) { debugPrint('[SA] fetchCurrentUser error: $e'); }`,
`  }`,
``,
`  Future<void> _loadAgents() async {`,
`    if (mounted) setState(() => _agentsLoading = true);`,
`    try {`,
`      final response = await Supabase.instance.client`,
`          .from('service_agents').select().order('created_at', ascending: false);`,
`      final agents = (response as List).map((j) => ServiceAgent.fromJson(j as Map<String, dynamic>)).toList();`,
`      if (mounted) {`,
`        setState(() {`,
`          _approvedAgents = agents.where((a) => a.approvalStatus == ServiceAgentApprovalStatus.approved).toList();`,
`          _pendingAgents = agents.where((a) => a.approvalStatus == ServiceAgentApprovalStatus.pending).toList();`,
`        });`,
`      }`,
`    } catch (e) { debugPrint('[SA] loadAgents: $e'); }`,
`    finally { if (mounted) setState(() => _agentsLoading = false); }`,
`  }`,
``,
`  Future<void> _loadDocumentsFromSupabase() async {`,
`    setState(() => _isLoading = true);`,
`    try {`,
`      final response = await Supabase.instance.client`,
`          .from('service_agent_documents').select().order('upload_date', ascending: false);`,
`      final docs = (response as List).map((json) => ServiceAgentDocument(`,
`        id: json['id']?.toString() ?? '',`,
`        agentName: json['agent_name']?.toString() ?? '',`,
`        serviceType: json['service_type']?.toString() ?? '',`,
`        mobileNumber: json['mobile_number']?.toString() ?? '',`,
`        documentName: json['document_type']?.toString() ?? '',`,
`        documentType: json['document_type']?.toString() ?? '',`,
`        uploadDate: DateTime.parse(json['upload_date']?.toString() ?? DateTime.now().toIso8601String()),`,
`        uploadedBy: json['uploaded_by']?.toString() ?? 'admin',`,
`        status: DocumentStatusExtension.fromString(json['status']?.toString() ?? 'active'),`,
`        description: json['description']?.toString() ?? '',`,
`        fileSize: json['file_size']?.toString() ?? '0 KB',`,
`        fileExtension: json['file_extension']?.toString() ?? 'pdf',`,
`        fileUrl: json['file_url']?.toString() ?? '',`,
`      )).toList();`,
`      setState(() { _allDocuments = docs; _applyFiltersAndSort(); });`,
`    } catch (e) { debugPrint('Error loading docs: $e'); }`,
`    finally { if (mounted) setState(() => _isLoading = false); }`,
`  }`,
``,
`  void _applyFiltersAndSort() {`,
`    List<ServiceAgentDocument> temp = List.from(_allDocuments);`,
`    final q = _searchController.text.trim().toLowerCase();`,
`    if (q.isNotEmpty) {`,
`      temp = temp.where((d) => d.agentName.toLowerCase().contains(q) || d.documentName.toLowerCase().contains(q) || d.documentType.toLowerCase().contains(q)).toList();`,
`    }`,
`    if (_selectedServiceType != 'All') temp = temp.where((d) => d.serviceType == _selectedServiceType).toList();`,
`    if (_selectedDocType != 'All') temp = temp.where((d) => d.documentType == _selectedDocType).toList();`,
`    if (_sortField != null) {`,
`      temp.sort((a, b) {`,
`        dynamic valA, valB;`,
`        switch (_sortField) {`,
`          case 'agentName': valA = a.agentName.toLowerCase(); valB = b.agentName.toLowerCase(); break;`,
`          case 'serviceType': valA = a.serviceType.toLowerCase(); valB = b.serviceType.toLowerCase(); break;`,
`          case 'uploadDate': valA = a.uploadDate; valB = b.uploadDate; break;`,
`          default: valA = a.uploadDate; valB = b.uploadDate;`,
`        }`,
`        int comp = valA.compareTo(valB);`,
`        return _sortAscending ? comp : -comp;`,
`      });`,
`    }`,
`    setState(() { _filteredDocuments = temp; _currentPage = 1; });`,
`  }`,
``,
`  void _resetFilters() {`,
`    _searchController.clear();`,
`    setState(() { _selectedServiceType = 'All'; _selectedDocType = 'All'; });`,
`    _applyFiltersAndSort();`,
`  }`,
``,
`  List<ServiceAgentDocument> get _paginatedDocuments {`,
`    int start = (_currentPage - 1) * _pageSize;`,
`    int end = (start + _pageSize).clamp(0, _filteredDocuments.length);`,
`    if (start >= _filteredDocuments.length) return [];`,
`    return _filteredDocuments.sublist(start, end);`,
`  }`,
`  int get _totalPages => (_filteredDocuments.length / _pageSize).ceil();`,
``,
`  // ── Add Agent Dialog ──────────────────────────────────────────────────────`,
`  void _showAddAgentDialog([ServiceAgent? existing]) {`,
`    final isEditing = existing != null;`,
`    final formKey = GlobalKey<FormState>();`,
`    final nameCtrl = TextEditingController(text: existing?.agentName);`,
`    final mobileCtrl = TextEditingController(text: existing?.mobileNumber);`,
`    String localServiceType = existing?.serviceType ?? 'Electrician';`,
`    DateTime? localDob = existing?.dateOfBirth;`,
`    String localImageUrl = existing?.agentImageUrl ?? '';`,
`    List<String> localAreas = List.from(existing?.areas ?? []);`,
``,
`    showDialog(`,
`      context: context,`,
`      barrierDismissible: false,`,
`      builder: (ctx) => StatefulBuilder(`,
`        builder: (ctx, setModal) => Dialog(`,
`          backgroundColor: CRMColors.surfaceElevatedOf(context),`,
`          insetPadding: const EdgeInsets.symmetric(horizontal: 24, vertical: 24),`,
`          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(CRMBorderRadius.dialog)),`,
`          child: ConstrainedBox(`,
`            constraints: const BoxConstraints(maxWidth: 560, maxHeight: 900),`,
`            child: Padding(`,
`              padding: const EdgeInsets.all(CRMSpacing.l),`,
`              child: Form(`,
`                key: formKey,`,
`                child: SingleChildScrollView(`,
`                  child: Column(`,
`                    mainAxisSize: MainAxisSize.min,`,
`                    crossAxisAlignment: CrossAxisAlignment.start,`,
`                    children: [`,
`                      Row(`,
`                        mainAxisAlignment: MainAxisAlignment.spaceBetween,`,
`                        children: [`,
`                          Text(isEditing ? 'Edit Agent' : 'Add Service Agent',`,
`                              style: CRMTypography.sectionTitle.copyWith(color: CRMColors.textOf(context))),`,
`                          IconButton(icon: const Icon(Icons.close_rounded), onPressed: () => Navigator.pop(ctx)),`,
`                        ],`,
`                      ),`,
`                      const SizedBox(height: CRMSpacing.m),`,
`                      Center(`,
`                        child: AgentImageUploadWidget(`,
`                          initialImageUrl: localImageUrl.isNotEmpty ? localImageUrl : null,`,
`                          onImageUploaded: (url) => setModal(() => localImageUrl = url),`,
`                        ),`,
`                      ),`,
`                      const SizedBox(height: CRMSpacing.l),`,
`                      CRMTextField(`,
`                        controller: nameCtrl,`,
`                        labelText: 'Agent Name *',`,
`                        hintText: 'e.g. Ramesh Kumar',`,
`                        validator: (v) => (v == null || v.trim().isEmpty) ? 'Agent name required' : null,`,
`                      ),`,
`                      const SizedBox(height: CRMSpacing.m),`,
`                      Row(children: [`,
`                        Expanded(child: CRMTextField(`,
`                          controller: mobileCtrl, labelText: 'Mobile Number *', hintText: '+91 XXXXX XXXXX',`,
`                          keyboardType: TextInputType.phone,`,
`                          validator: (v) => (v == null || v.trim().isEmpty) ? 'Required' : null,`,
`                        )),`,
`                        const SizedBox(width: CRMSpacing.m),`,
`                        Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [`,
`                          Text('Service Type (Role) *', style: CRMTypography.label.copyWith(color: CRMColors.textSecondaryOf(context))),`,
`                          const SizedBox(height: CRMSpacing.xs),`,
`                          DropdownButtonFormField<String>(`,
`                            value: localServiceType, isExpanded: true,`,
`                            dropdownColor: CRMColors.surfaceElevatedOf(context),`,
`                            decoration: InputDecoration(`,
`                              contentPadding: const EdgeInsets.symmetric(horizontal: CRMSpacing.m, vertical: CRMSpacing.s),`,
`                              filled: true, fillColor: CRMColors.cardBgOf(context),`,
`                              border: OutlineInputBorder(borderRadius: BorderRadius.circular(CRMBorderRadius.input), borderSide: BorderSide(color: CRMColors.borderOf(context))),`,
`                            ),`,
`                            items: _serviceTypes.where((t) => t != 'All').map((t) => DropdownMenuItem(value: t, child: Text(t, style: TextStyle(color: CRMColors.textOf(context))))).toList(),`,
`                            onChanged: (v) { if (v != null) setModal(() => localServiceType = v); },`,
`                          ),`,
`                        ])),`,
`                      ]),`,
`                      const SizedBox(height: CRMSpacing.m),`,
`                      Column(crossAxisAlignment: CrossAxisAlignment.start, children: [`,
`                        Text('Date of Birth', style: CRMTypography.label.copyWith(color: CRMColors.textSecondaryOf(context))),`,
`                        const SizedBox(height: CRMSpacing.xs),`,
`                        InkWell(`,
`                          onTap: () async {`,
`                            final picked = await showDatePicker(`,
`                              context: context,`,
`                              initialDate: localDob ?? DateTime(1990),`,
`                              firstDate: DateTime(1940),`,
`                              lastDate: DateTime.now(),`,
`                            );`,
`                            if (picked != null) setModal(() => localDob = picked);`,
`                          },`,
`                          child: Container(`,
`                            padding: const EdgeInsets.symmetric(horizontal: CRMSpacing.m, vertical: 14),`,
`                            decoration: BoxDecoration(`,
`                              color: CRMColors.cardBgOf(context),`,
`                              borderRadius: BorderRadius.circular(CRMBorderRadius.input),`,
`                              border: Border.all(color: CRMColors.borderOf(context)),`,
`                            ),`,
`                            child: Row(children: [`,
`                              Icon(Icons.calendar_today_rounded, size: 16, color: CRMColors.textSecondaryOf(context)),`,
`                              const SizedBox(width: 8),`,
`                              Text(`,
`                                localDob != null ? DateFormat('dd MMM yyyy').format(localDob!) : 'Select date of birth',`,
`                                style: CRMTypography.body.copyWith(color: localDob != null ? CRMColors.textOf(context) : CRMColors.textMutedOf(context)),`,
`                              ),`,
`                            ]),`,
`                          ),`,
`                        ),`,
`                        if (localDob != null)`,
`                          TextButton.icon(`,
`                            onPressed: () => setModal(() => localDob = null),`,
`                            icon: const Icon(Icons.clear_rounded, size: 14),`,
`                            label: const Text('Clear', style: TextStyle(fontSize: 12)),`,
`                            style: TextButton.styleFrom(padding: EdgeInsets.zero),`,
`                          ),`,
`                      ]),`,
`                      const SizedBox(height: CRMSpacing.m),`,
`                      AreaMultiSelectWidget(`,
`                        selectedAreas: localAreas,`,
`                        onChanged: (areas) => setModal(() => localAreas = areas),`,
`                      ),`,
`                      const SizedBox(height: CRMSpacing.l),`,
`                      Row(mainAxisAlignment: MainAxisAlignment.end, children: [`,
`                        CRMButton(label: 'Cancel', variant: CRMButtonVariant.outline, onPressed: () => Navigator.pop(ctx)),`,
`                        const SizedBox(width: CRMSpacing.s),`,
`                        CRMButton(`,
`                          label: isEditing ? 'Save Changes' : (_isAdmin ? 'Add Agent' : 'Submit for Approval'),`,
`                          variant: CRMButtonVariant.primary,`,
`                          onPressed: () async {`,
`                            if (!formKey.currentState!.validate()) return;`,
`                            if (localAreas.isEmpty) {`,
`                              ScaffoldMessenger.of(context).showSnackBar(const SnackBar(`,
`                                content: Text('Please select at least one service area.'),`,
`                                backgroundColor: CRMColors.danger,`,
`                              ));`,
`                              return;`,
`                            }`,
`                            final approvalStatus = _isAdmin ? 'approved' : 'pending';`,
`                            final now = DateTime.now().toUtc().toIso8601String();`,
`                            try {`,
`                              if (isEditing) {`,
`                                await Supabase.instance.client.from('service_agents').update({`,
`                                  'agent_name': nameCtrl.text.trim(),`,
`                                  'mobile_number': mobileCtrl.text.trim(),`,
`                                  'service_type': localServiceType,`,
`                                  'date_of_birth': localDob?.toIso8601String().split('T').first,`,
`                                  'agent_image_url': localImageUrl.isNotEmpty ? localImageUrl : null,`,
`                                  'areas': localAreas,`,
`                                  'updated_at': now,`,
`                                }).eq('id', existing.id);`,
`                              } else {`,
`                                await Supabase.instance.client.from('service_agents').insert({`,
`                                  'id': generateUuidV4(),`,
`                                  'agent_name': nameCtrl.text.trim(),`,
`                                  'mobile_number': mobileCtrl.text.trim(),`,
`                                  'service_type': localServiceType,`,
`                                  'date_of_birth': localDob?.toIso8601String().split('T').first,`,
`                                  'agent_image_url': localImageUrl.isNotEmpty ? localImageUrl : null,`,
`                                  'areas': localAreas,`,
`                                  'approval_status': approvalStatus,`,
`                                  'added_by_user_id': _currentUserId,`,
`                                  'added_by_name': _currentUserName,`,
`                                  'created_at': now,`,
`                                  'updated_at': now,`,
`                                });`,
`                              }`,
`                              if (!ctx.mounted) return;`,
`                              Navigator.pop(ctx);`,
`                              await _loadAgents();`,
`                              if (!mounted) return;`,
`                              ScaffoldMessenger.of(this.context).showSnackBar(SnackBar(`,
`                                content: Text(isEditing ? 'Agent updated!' : (_isAdmin ? 'Agent added!' : 'Submitted for approval!')),`,
`                                backgroundColor: CRMColors.success, behavior: SnackBarBehavior.floating,`,
`                              ));`,
`                              if (!isEditing && !_isAdmin) _tabController.animateTo(1);`,
`                            } catch (e) {`,
`                              if (!ctx.mounted) return;`,
`                              ScaffoldMessenger.of(ctx).showSnackBar(SnackBar(content: Text('Save failed: $e'), backgroundColor: CRMColors.danger));`,
`                            }`,
`                          },`,
`                        ),`,
`                      ]),`,
`                    ],`,
`                  ),`,
`                ),`,
`              ),`,
`            ),`,
`          ),`,
`        ),`,
`      ),`,
`    );`,
`  }`,
``,
`  Future<void> _approveAgent(ServiceAgent agent) async {`,
`    try {`,
`      await Supabase.instance.client.from('service_agents').update({`,
`        'approval_status': 'approved',`,
`        'approved_by_name': _currentUserName,`,
`        'approved_at': DateTime.now().toUtc().toIso8601String(),`,
`      }).eq('id', agent.id);`,
`      await _loadAgents();`,
`      if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('\${agent.agentName} approved!'), backgroundColor: CRMColors.success, behavior: SnackBarBehavior.floating));`,
`    } catch (e) { debugPrint('[ApproveAgent] $e'); }`,
`  }`,
``,
`  Future<void> _rejectAgent(ServiceAgent agent) async {`,
`    final confirm = await CRMDialogs.showDeleteConfirmation(context, title: 'Reject Agent', content: 'Reject "\${agent.agentName}"? This will remove them from the pending list.');`,
`    if (confirm != true) return;`,
`    try {`,
`      await Supabase.instance.client.from('service_agents').update({'approval_status': 'rejected'}).eq('id', agent.id);`,
`      await _loadAgents();`,
`      if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('\${agent.agentName} rejected.'), backgroundColor: CRMColors.danger, behavior: SnackBarBehavior.floating));`,
`    } catch (e) { debugPrint('[RejectAgent] $e'); }`,
`  }`,
``,
`  Future<void> _deleteAgent(ServiceAgent agent) async {`,
`    final confirm = await CRMDialogs.showDeleteConfirmation(context, title: 'Delete Agent', content: 'Delete "\${agent.agentName}"?');`,
`    if (confirm != true) return;`,
`    try {`,
`      await Supabase.instance.client.from('service_agents').delete().eq('id', agent.id);`,
`      await _loadAgents();`,
`    } catch (e) { debugPrint('[DeleteAgent] $e'); }`,
`  }`,
``,
`  void _viewDocument(ServiceAgentDocument doc) {`,
`    showDialog(context: context, builder: (context) => Dialog(`,
`      backgroundColor: CRMColors.surfaceElevatedOf(context),`,
`      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(CRMBorderRadius.dialog)),`,
`      child: ConstrainedBox(constraints: const BoxConstraints(maxWidth: 550), child: Padding(`,
`        padding: const EdgeInsets.all(CRMSpacing.l),`,
`        child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [`,
`          Row(children: [`,
`            FileIconHelper.getIconForExtension(doc.fileExtension, size: 28),`,
`            const SizedBox(width: CRMSpacing.s),`,
`            Expanded(child: Text(doc.documentName, style: CRMTypography.sectionTitle.copyWith(color: CRMColors.textOf(context)), maxLines: 1, overflow: TextOverflow.ellipsis)),`,
`            CRMStatusChip(status: doc.status.displayName),`,
`          ]),`,
`          const Divider(height: CRMSpacing.xl),`,
`          _buildDetailRow(context, 'Agent Name:', doc.agentName),`,
`          _buildDetailRow(context, 'Service Type:', doc.serviceType),`,
`          _buildDetailRow(context, 'Mobile Number:', doc.mobileNumber),`,
`          _buildDetailRow(context, 'Document Type:', doc.documentType),`,
`          _buildDetailRow(context, 'Uploaded On:', DateFormat('dd MMM yyyy, hh:mm a').format(doc.uploadDate)),`,
`          _buildDetailRow(context, 'Uploaded By:', doc.uploadedBy),`,
`          const SizedBox(height: CRMSpacing.l),`,
`          Row(mainAxisAlignment: MainAxisAlignment.end, children: [`,
`            CRMButton(label: 'Close', variant: CRMButtonVariant.outline, onPressed: () => Navigator.pop(context)),`,
`            if (doc.fileUrl != null && doc.fileUrl!.startsWith('http')) ... [`,
`              const SizedBox(width: CRMSpacing.s),`,
`              CRMButton(label: 'Open Document', variant: CRMButtonVariant.primary, prefixIcon: Icons.open_in_new_rounded,`,
`                onPressed: () async {`,
`                  var openUrl = doc.fileUrl!;`,
`                  if (openUrl.contains('res.cloudinary.com') && openUrl.toLowerCase().contains('.pdf') && openUrl.contains('/upload/') && !openUrl.contains('/upload/f_')) {`,
`                    openUrl = openUrl.replaceFirst('/upload/', '/upload/f_jpg/');`,
`                  }`,
`                  final uri = Uri.parse(openUrl);`,
`                  if (await canLaunchUrl(uri)) await launchUrl(uri, mode: LaunchMode.externalApplication);`,
`                }),`,
`            ],`,
`          ]),`,
`        ]),`,
`      )),`,
`    ));`,
`  }`,
``,
`  Widget _buildDetailRow(BuildContext context, String label, String value) {`,
`    return Padding(`,
`      padding: const EdgeInsets.symmetric(vertical: 4.0),`,
`      child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [`,
`        SizedBox(width: 140, child: Text(label, style: CRMTypography.captionBold.copyWith(color: CRMColors.textSecondaryOf(context)))),`,
`        Expanded(child: Text(value, style: CRMTypography.bodyMedium.copyWith(color: CRMColors.textOf(context)))),`,
`      ]),`,
`    );`,
`  }`,
``,
`  void _deleteDocument(ServiceAgentDocument doc) async {`,
`    final confirm = await CRMDialogs.showDeleteConfirmation(context, title: 'Delete Agent Document', content: 'Delete "\${doc.documentName}"?');`,
`    if (confirm != true) return;`,
`    try {`,
`      await Supabase.instance.client.from('service_agent_documents').delete().eq('id', doc.id);`,
`      setState(() { _allDocuments.removeWhere((d) => d.id == doc.id); _applyFiltersAndSort(); });`,
`      if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('"\${doc.documentName}" deleted.'), backgroundColor: CRMColors.danger, behavior: SnackBarBehavior.floating));`,
`    } catch (e) { debugPrint('Delete doc error: $e'); }`,
`  }`,
``,
`  void _showUploadEditDialog([ServiceAgentDocument? existingDoc]) {`,
`    final isEditing = existingDoc != null;`,
`    final formKey = GlobalKey<FormState>();`,
`    final agentController = TextEditingController(text: existingDoc?.agentName);`,
`    final mobileController = TextEditingController(text: existingDoc?.mobileNumber);`,
`    final descController = TextEditingController(text: existingDoc?.description);`,
`    String localServiceType = existingDoc?.serviceType ?? 'Electrician';`,
`    String localDocType = existingDoc?.documentType ?? 'Aadhaar Card';`,
`    bool showCustomField = false;`,
`    final customDocTypeController = TextEditingController();`,
`    DocumentStatus localStatus = existingDoc?.status ?? DocumentStatus.active;`,
`    String localFileName = existingDoc?.documentName ?? '';`,
`    String localFileExt = existingDoc?.fileExtension ?? 'pdf';`,
`    String localFileSize = existingDoc?.fileSize ?? '0 KB';`,
`    String localFileUrl = existingDoc?.fileUrl ?? '';`,
``,
`    showDialog(`,
`      context: context,`,
`      barrierDismissible: false,`,
`      builder: (context) => StatefulBuilder(`,
`        builder: (context, setModalState) => Dialog(`,
`          backgroundColor: CRMColors.surfaceElevatedOf(context),`,
`          insetPadding: const EdgeInsets.symmetric(horizontal: 24, vertical: 24),`,
`          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(CRMBorderRadius.dialog)),`,
`          child: ConstrainedBox(`,
`            constraints: const BoxConstraints(maxWidth: 550, maxHeight: 850),`,
`            child: Padding(`,
`              padding: const EdgeInsets.all(CRMSpacing.l),`,
`              child: Form(`,
`                key: formKey,`,
`                child: SingleChildScrollView(`,
`                  child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [`,
`                    Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [`,
`                      Text(isEditing ? 'Edit Agent Document' : 'Upload Agent Document', style: CRMTypography.sectionTitle.copyWith(color: CRMColors.textOf(context))),`,
`                      IconButton(icon: const Icon(Icons.close_rounded), onPressed: () => Navigator.pop(context)),`,
`                    ]),`,
`                    const SizedBox(height: CRMSpacing.m),`,
`                    CRMTextField(controller: agentController, labelText: 'Agent Name *', hintText: 'e.g. A1 Electricians Ltd',`,
`                        validator: (val) => val == null || val.trim().isEmpty ? 'Agent name required' : null),`,
`                    const SizedBox(height: CRMSpacing.m),`,
`                    Row(children: [`,
`                      Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [`,
`                        Text('Service Type *', style: CRMTypography.label.copyWith(color: CRMColors.textSecondaryOf(context))),`,
`                        const SizedBox(height: CRMSpacing.xs),`,
`                        DropdownButtonFormField<String>(`,
`                          value: localServiceType, isExpanded: true,`,
`                          dropdownColor: CRMColors.surfaceElevatedOf(context),`,
`                          decoration: InputDecoration(`,
`                            contentPadding: const EdgeInsets.symmetric(horizontal: CRMSpacing.m, vertical: CRMSpacing.s),`,
`                            filled: true, fillColor: CRMColors.cardBgOf(context),`,
`                            border: OutlineInputBorder(borderRadius: BorderRadius.circular(CRMBorderRadius.input), borderSide: BorderSide(color: CRMColors.borderOf(context))),`,
`                          ),`,
`                          items: _serviceTypes.where((t) => t != 'All').map((t) => DropdownMenuItem(value: t, child: Text(t, style: TextStyle(color: CRMColors.textOf(context))))).toList(),`,
`                          onChanged: (val) { if (val != null) setModalState(() => localServiceType = val); },`,
`                        ),`,
`                      ])),`,
`                      const SizedBox(width: CRMSpacing.m),`,
`                      Expanded(child: CRMTextField(controller: mobileController, labelText: 'Mobile Number *', hintText: '+91 XXXXX XXXXX',`,
`                          keyboardType: TextInputType.phone, validator: (val) => val == null || val.trim().isEmpty ? 'Required' : null)),`,
`                    ]),`,
`                    const SizedBox(height: CRMSpacing.m),`,
`                    Column(crossAxisAlignment: CrossAxisAlignment.start, children: [`,
`                      Text('Document Type *', style: CRMTypography.label.copyWith(color: CRMColors.textSecondaryOf(context))),`,
`                      const SizedBox(height: CRMSpacing.xs),`,
`                      Row(children: [`,
`                        Expanded(child: DropdownButtonFormField<String>(`,
`                          value: ['Aadhaar Card', 'Other'].contains(localDocType) ? localDocType : 'Other',`,
`                          isExpanded: true, dropdownColor: CRMColors.surfaceElevatedOf(context),`,
`                          decoration: InputDecoration(`,
`                            contentPadding: const EdgeInsets.symmetric(horizontal: CRMSpacing.m, vertical: CRMSpacing.s),`,
`                            filled: true, fillColor: CRMColors.cardBgOf(context),`,
`                            border: OutlineInputBorder(borderRadius: BorderRadius.circular(CRMBorderRadius.input), borderSide: BorderSide(color: CRMColors.borderOf(context))),`,
`                          ),`,
`                          items: ['Aadhaar Card', 'Other'].map((t) => DropdownMenuItem(value: t, child: Text(t, style: TextStyle(color: CRMColors.textOf(context))))).toList(),`,
`                          onChanged: (val) { if (val != null) setModalState(() { localDocType = val; showCustomField = val == 'Other'; }); },`,
`                        )),`,
`                        const SizedBox(width: CRMSpacing.s),`,
`                        IconButton(`,
`                          icon: Icon(showCustomField ? Icons.remove_circle_outline_rounded : Icons.add_circle_outline_rounded, color: CRMColors.primaryOf(context)),`,
`                          onPressed: () { setModalState(() { showCustomField = !showCustomField; localDocType = showCustomField ? 'Other' : 'Aadhaar Card'; }); },`,
`                        ),`,
`                      ]),`,
`                      if (showCustomField) ... [`,
`                        const SizedBox(height: CRMSpacing.m),`,
`                        CRMTextField(controller: customDocTypeController, labelText: 'Custom Document Type *', hintText: 'e.g. GST Certificate',`,
`                            validator: (val) => val == null || val.trim().isEmpty ? 'Required' : null),`,
`                      ],`,
`                    ]),`,
`                    const SizedBox(height: CRMSpacing.m),`,
`                    CRMTextField(controller: descController, labelText: 'Description', hintText: 'Add description or registration validity notes...', maxLines: 2),`,
`                    const SizedBox(height: CRMSpacing.m),`,
`                    DragDropUploadZone(`,
`                      initialFileName: localFileName, initialFileSize: localFileSize,`,
`                      onOcrDetected: (name) => setModalState(() => agentController.text = name),`,
`                      onFileSelected: (name, ext, size, url) => setModalState(() { localFileName = name; localFileExt = ext; localFileSize = size; localFileUrl = url; }),`,
`                    ),`,
`                    const SizedBox(height: CRMSpacing.m),`,
`                    Row(mainAxisAlignment: MainAxisAlignment.end, children: [`,
`                      CRMButton(label: 'Cancel', variant: CRMButtonVariant.outline, onPressed: () => Navigator.pop(context)),`,
`                      const SizedBox(width: CRMSpacing.s),`,
`                      CRMButton(`,
`                        label: isEditing ? 'Save Changes' : 'Upload',`,
`                        variant: CRMButtonVariant.primary,`,
`                        onPressed: () async {`,
`                          if (!formKey.currentState!.validate()) return;`,
`                          if (localFileName.isEmpty) { ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Please upload a document file.'), backgroundColor: CRMColors.danger)); return; }`,
`                          if (localFileUrl.isEmpty || !localFileUrl.contains('res.cloudinary.com')) { ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Document must be uploaded to Cloudinary first.'), backgroundColor: CRMColors.danger)); return; }`,
`                          final docType = showCustomField ? customDocTypeController.text.trim() : localDocType;`,
`                          String uploadedByName = 'Admin';`,
`                          try {`,
`                            final cu = Supabase.instance.client.auth.currentUser;`,
`                            if (cu != null) {`,
`                              final p = await Supabase.instance.client.from('users').select('full_name, roles(name)').eq('id', cu.id).maybeSingle();`,
`                              if (p != null) { final r = p['roles']?['name']?.toString(); final n = p['full_name']?.toString(); uploadedByName = r == 'Admin' ? 'Admin' : r == 'Super Admin' ? 'Super Admin' : (n ?? cu.email ?? 'Admin'); }`,
`                            }`,
`                          } catch (_) {}`,
`                          try {`,
`                            if (isEditing) {`,
`                              await Supabase.instance.client.from('service_agent_documents').update({`,
`                                'agent_name': agentController.text.trim(), 'service_type': localServiceType, 'mobile_number': mobileController.text.trim(),`,
`                                'document_type': docType, 'description': descController.text.trim(), 'status': localStatus.displayName.toLowerCase(),`,
`                                'file_size': localFileSize, 'file_extension': localFileExt, 'file_url': localFileUrl, 'uploaded_by': uploadedByName,`,
`                              }).eq('id', existingDoc.id);`,
`                            } else {`,
`                              await Supabase.instance.client.from('service_agent_documents').insert({`,
`                                'id': generateUuidV4(), 'agent_name': agentController.text.trim(), 'service_type': localServiceType,`,
`                                'mobile_number': mobileController.text.trim(), 'document_type': docType, 'description': descController.text.trim(),`,
`                                'status': localStatus.displayName.toLowerCase(), 'file_size': localFileSize, 'file_extension': localFileExt,`,
`                                'file_url': localFileUrl, 'upload_date': DateTime.now().toUtc().toIso8601String(), 'uploaded_by': uploadedByName,`,
`                              });`,
`                            }`,
`                            if (!context.mounted) return;`,
`                            Navigator.pop(context);`,
`                            await _loadDocumentsFromSupabase();`,
`                            if (!mounted) return;`,
`                            ScaffoldMessenger.of(this.context).showSnackBar(SnackBar(content: Text(isEditing ? 'Document updated!' : 'Document uploaded!'), backgroundColor: CRMColors.success, behavior: SnackBarBehavior.floating));`,
`                          } catch (err) {`,
`                            if (!context.mounted) return;`,
`                            ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Save failed: $err'), backgroundColor: CRMColors.danger));`,
`                          }`,
`                        },`,
`                      ),`,
`                    ]),`,
`                  ]),`,
`                ),`,
`              ),`,
`            ),`,
`          ),`,
`        ),`,
`      ),`,
`    );`,
`  }`,
``,
`  @override`,
`  Widget build(BuildContext context) {`,
`    final size = MediaQuery.of(context).size;`,
`    final isDesktop = size.width >= 1024;`,
`    final isTablet = size.width >= 600 && size.width < 1024;`,
`    final isMobile = size.width < 600;`,
``,
`    return Scaffold(`,
`      backgroundColor: CRMColors.background,`,
`      body: SafeArea(`,
`        child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [`,
`          Padding(`,
`            padding: const EdgeInsets.fromLTRB(CRMSpacing.m, CRMSpacing.m, CRMSpacing.m, 0),`,
`            child: Row(`,
`              mainAxisAlignment: MainAxisAlignment.spaceBetween,`,
`              children: [`,
`                Column(crossAxisAlignment: CrossAxisAlignment.start, children: [`,
`                  const LibraryBreadcrumb(currentPageName: 'Service Agent Library'),`,
`                  Text('Service agents', style: CRMTypography.pageTitle.copyWith(color: CRMColors.textOf(context))),`,
`                  Text('Store, filter, and organize service provider SLA agreements and invoices.',`,
`                      style: CRMTypography.caption.copyWith(color: CRMColors.textSecondaryOf(context))),`,
`                ]),`,
`                Row(children: [`,
`                  PopupMenuButton<String>(`,
`                    icon: Icon(Icons.download_rounded, color: CRMColors.primaryOf(context)),`,
`                    tooltip: 'Export Index',`,
`                    onSelected: (val) => DocumentExportHelper.triggerExport(context, val),`,
`                    itemBuilder: (context) => [`,
`                      const PopupMenuItem(value: 'Excel', child: Text('Export to Excel')),`,
`                      const PopupMenuItem(value: 'PDF', child: Text('Export to PDF')),`,
`                    ],`,
`                  ),`,
`                  const SizedBox(width: CRMSpacing.s),`,
`                  CRMButton(label: 'Add agent', prefixIcon: Icons.add_rounded, onPressed: () => _showAddAgentDialog()),`,
`                ]),`,
`              ],`,
`            ),`,
`          ),`,
`          const SizedBox(height: CRMSpacing.s),`,
`          Padding(`,
`            padding: const EdgeInsets.symmetric(horizontal: CRMSpacing.m),`,
`            child: Wrap(spacing: CRMSpacing.m, children: [`,
`              SizedBox(`,
`                width: isDesktop ? 220 : double.infinity,`,
`                child: CRMKPICard(title: 'Total Approved Agents', value: '\${_approvedAgents.length}', icon: Icons.badge_rounded, iconColor: CRMColors.primaryOf(context), benefit: 'Approved agents ready to work'),`,
`              ),`,
`              if (_pendingAgents.isNotEmpty)`,
`                SizedBox(`,
`                  width: isDesktop ? 220 : double.infinity,`,
`                  child: CRMKPICard(title: 'Pending Approval', value: '\${_pendingAgents.length}', icon: Icons.pending_actions_rounded, iconColor: Colors.orange, benefit: 'Awaiting admin review'),`,
`                ),`,
`            ]),`,
`          ),`,
`          const SizedBox(height: CRMSpacing.m),`,
`          Padding(`,
`            padding: const EdgeInsets.symmetric(horizontal: CRMSpacing.m),`,
`            child: TabBar(`,
`              controller: _tabController,`,
`              labelStyle: CRMTypography.bodyMedium.copyWith(fontWeight: FontWeight.w600),`,
`              unselectedLabelStyle: CRMTypography.body,`,
`              labelColor: CRMColors.primaryOf(context),`,
`              unselectedLabelColor: CRMColors.textSecondaryOf(context),`,
`              indicatorColor: CRMColors.primaryOf(context),`,
`              indicatorWeight: 2.5,`,
`              tabs: [`,
`                const Tab(text: 'Agents'),`,
`                Tab(child: Row(mainAxisSize: MainAxisSize.min, children: [`,
`                  const Text('Pending'),`,
`                  if (_pendingAgents.isNotEmpty) ... [`,
`                    const SizedBox(width: 6),`,
`                    Container(`,
`                      padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),`,
`                      decoration: BoxDecoration(color: Colors.orange, borderRadius: BorderRadius.circular(10)),`,
`                      child: Text('\${_pendingAgents.length}', style: const TextStyle(color: Colors.white, fontSize: 10, fontWeight: FontWeight.bold)),`,
`                    ),`,
`                  ],`,
`                ])),`,
`                const Tab(text: 'Documents'),`,
`              ],`,
`            ),`,
`          ),`,
`          Expanded(child: TabBarView(controller: _tabController, children: [`,
`            _buildApprovedAgentsTab(),`,
`            _buildPendingTab(),`,
`            _buildDocumentsTab(isDesktop, isTablet, isMobile),`,
`          ])),`,
`        ]),`,
`      ),`,
`    );`,
`  }`,
``,
`  Widget _buildApprovedAgentsTab() {`,
`    if (_agentsLoading) return const Center(child: CircularProgressIndicator());`,
`    if (_approvedAgents.isEmpty) return CRMEmptyState(title: 'No Approved Agents', description: 'No agents approved yet. Use "Add agent" to add one.', actionLabel: 'Add Agent', onActionPressed: () => _showAddAgentDialog());`,
`    return ListView.builder(`,
`      padding: const EdgeInsets.all(CRMSpacing.m),`,
`      itemCount: _approvedAgents.length,`,
`      itemBuilder: (ctx, i) => _buildAgentCard(_approvedAgents[i], isPending: false),`,
`    );`,
`  }`,
``,
`  Widget _buildPendingTab() {`,
`    if (_agentsLoading) return const Center(child: CircularProgressIndicator());`,
`    if (_pendingAgents.isEmpty) return const CRMEmptyState(title: 'No Pending Agents', description: 'All agents reviewed. New submissions appear here.');`,
`    return ListView.builder(`,
`      padding: const EdgeInsets.all(CRMSpacing.m),`,
`      itemCount: _pendingAgents.length,`,
`      itemBuilder: (ctx, i) => _buildAgentCard(_pendingAgents[i], isPending: true),`,
`    );`,
`  }`,
``,
`  Widget _buildAgentCard(ServiceAgent agent, {required bool isPending}) {`,
`    return Padding(`,
`      padding: const EdgeInsets.only(bottom: CRMSpacing.m),`,
`      child: CRMCard(`,
`        padding: const EdgeInsets.all(CRMSpacing.m),`,
`        child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [`,
`          Row(children: [`,
`            Container(`,
`              width: 52, height: 52,`,
`              decoration: BoxDecoration(shape: BoxShape.circle, color: CRMColors.cardBgOf(context),`,
`                  border: Border.all(color: CRMColors.primaryOf(context).withOpacity(0.3), width: 2)),`,
`              clipBehavior: Clip.antiAlias,`,
`              child: agent.agentImageUrl != null && agent.agentImageUrl!.isNotEmpty`,
`                  ? Image.network(agent.agentImageUrl!, fit: BoxFit.cover, errorBuilder: (_, __, ___) => Icon(Icons.person_rounded, size: 28, color: CRMColors.textMutedOf(context)))`,
`                  : Icon(Icons.person_rounded, size: 28, color: CRMColors.textMutedOf(context)),`,
`            ),`,
`            const SizedBox(width: CRMSpacing.m),`,
`            Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [`,
`              Text(agent.agentName, style: CRMTypography.bodyMedium.copyWith(fontWeight: FontWeight.bold, color: CRMColors.textOf(context))),`,
`              const SizedBox(height: 2),`,
`              Row(children: [`,
`                Container(`,
`                  padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 2),`,
`                  decoration: BoxDecoration(color: CRMColors.primaryOf(context).withOpacity(0.1), borderRadius: BorderRadius.circular(12)),`,
`                  child: Text(agent.serviceType, style: TextStyle(fontSize: 11, color: CRMColors.primaryOf(context), fontWeight: FontWeight.w600)),`,
`                ),`,
`                const SizedBox(width: 6),`,
`                Icon(Icons.phone_rounded, size: 12, color: CRMColors.textMutedOf(context)),`,
`                const SizedBox(width: 2),`,
`                Text(agent.mobileNumber, style: CRMTypography.caption.copyWith(color: CRMColors.textSecondaryOf(context))),`,
`              ]),`,
`            ])),`,
`            if (isPending && _isAdmin) ... [`,
`              IconButton(`,
`                icon: Container(padding: const EdgeInsets.all(6), decoration: BoxDecoration(color: CRMColors.success.withOpacity(0.1), borderRadius: BorderRadius.circular(8)),`,
`                    child: const Icon(Icons.check_rounded, color: CRMColors.success, size: 18)),`,
`                tooltip: 'Approve', onPressed: () => _approveAgent(agent),`,
`              ),`,
`              IconButton(`,
`                icon: Container(padding: const EdgeInsets.all(6), decoration: BoxDecoration(color: CRMColors.danger.withOpacity(0.1), borderRadius: BorderRadius.circular(8)),`,
`                    child: const Icon(Icons.close_rounded, color: CRMColors.danger, size: 18)),`,
`                tooltip: 'Reject', onPressed: () => _rejectAgent(agent),`,
`              ),`,
`            ] else if (!isPending) ...[  `,
`              PopupMenuButton<String>(`,
`                icon: Icon(Icons.more_vert_rounded, color: CRMColors.textSecondaryOf(context)),`,
`                onSelected: (val) { if (val == 'edit') _showAddAgentDialog(agent); if (val == 'delete') _deleteAgent(agent); },`,
`                itemBuilder: (ctx) => [`,
`                  const PopupMenuItem(value: 'edit', child: Row(children: [Icon(Icons.edit_outlined, size: 18), SizedBox(width: 8), Text('Edit')])),`,
`                  const PopupMenuDivider(),`,
`                  const PopupMenuItem(value: 'delete', child: Row(children: [Icon(Icons.delete_outline_rounded, color: CRMColors.danger, size: 18), SizedBox(width: 8), Text('Delete', style: TextStyle(color: CRMColors.danger))])),`,
`                ],`,
`              ),`,
`            ],`,
`          ]),`,
`          if (agent.areas.isNotEmpty) ... [`,
`            const SizedBox(height: CRMSpacing.s),`,
`            const Divider(height: 1),`,
`            const SizedBox(height: CRMSpacing.s),`,
`            Row(crossAxisAlignment: CrossAxisAlignment.start, children: [`,
`              Icon(Icons.location_on_rounded, size: 14, color: CRMColors.textMutedOf(context)),`,
`              const SizedBox(width: 4),`,
`              Expanded(child: Wrap(spacing: 4, runSpacing: 4, children: agent.areas.map((a) => Container(`,
`                padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),`,
`                decoration: BoxDecoration(color: CRMColors.backgroundOf(context), borderRadius: BorderRadius.circular(6), border: Border.all(color: CRMColors.borderOf(context))),`,
`                child: Text(a, style: CRMTypography.caption.copyWith(color: CRMColors.textSecondaryOf(context))),`,
`              )).toList())),`,
`            ]),`,
`          ],`,
`          if (agent.dateOfBirth != null) ... [`,
`            const SizedBox(height: CRMSpacing.xs),`,
`            Row(children: [`,
`              Icon(Icons.cake_rounded, size: 13, color: CRMColors.textMutedOf(context)),`,
`              const SizedBox(width: 4),`,
`              Text('DOB: \${DateFormat('dd MMM yyyy').format(agent.dateOfBirth!)}', style: CRMTypography.caption.copyWith(color: CRMColors.textSecondaryOf(context))),`,
`            ]),`,
`          ],`,
`          if (isPending) ... [`,
`            const SizedBox(height: CRMSpacing.s),`,
`            Row(children: [`,
`              Icon(Icons.person_outline_rounded, size: 13, color: CRMColors.textMutedOf(context)),`,
`              const SizedBox(width: 4),`,
`              Text('Added by: \${agent.addedByName}', style: CRMTypography.caption.copyWith(color: CRMColors.textSecondaryOf(context))),`,
`              const SizedBox(width: 12),`,
`              Icon(Icons.access_time_rounded, size: 13, color: CRMColors.textMutedOf(context)),`,
`              const SizedBox(width: 4),`,
`              Text(DateFormat('dd MMM yyyy').format(agent.createdAt), style: CRMTypography.caption.copyWith(color: CRMColors.textSecondaryOf(context))),`,
`            ]),`,
`          ],`,
`        ]),`,
`      ),`,
`    );`,
`  }`,
``,
`  Widget _buildDocumentsTab(bool isDesktop, bool isTablet, bool isMobile) {`,
`    return SingleChildScrollView(`,
`      padding: const EdgeInsets.all(CRMSpacing.m),`,
`      child: Column(children: [`,
`        CRMCard(`,
`          padding: const EdgeInsets.all(CRMSpacing.m),`,
`          child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [`,
`            Row(children: [`,
`              Icon(Icons.filter_alt_rounded, size: 18, color: CRMColors.primaryOf(context)),`,
`              const SizedBox(width: 6),`,
`              Text('Advanced Filters', style: CRMTypography.bodyMedium.copyWith(fontWeight: FontWeight.bold, color: CRMColors.textOf(context))),`,
`              const Spacer(),`,
`              TextButton(onPressed: _resetFilters, child: const Text('Reset All')),`,
`            ]),`,
`            const SizedBox(height: CRMSpacing.s),`,
`            LayoutBuilder(builder: (ctx, cons) {`,
`              int cols = isDesktop ? 3 : (isTablet ? 3 : 2);`,
`              double sp = CRMSpacing.s;`,
`              double w = ((cons.maxWidth - (sp * (cols - 1))) / cols) - 1.0;`,
`              return Wrap(spacing: sp, runSpacing: sp, children: [`,
`                SizedBox(width: w, child: TextField(`,
`                  controller: _searchController, style: const TextStyle(fontSize: 13),`,
`                  decoration: InputDecoration(hintText: 'Search Agent or Document', prefixIcon: const Icon(Icons.search_rounded, size: 18),`,
`                      contentPadding: const EdgeInsets.symmetric(horizontal: 10, vertical: 10), border: OutlineInputBorder(borderRadius: BorderRadius.circular(6))),`,
`                  onChanged: (_) => _applyFiltersAndSort(),`,
`                )),`,
`                _buildFilterDropdown('Service Type', _selectedServiceType, _serviceTypes, (val) { setState(() => _selectedServiceType = val!); _applyFiltersAndSort(); }, w),`,
`                _buildFilterDropdown('Doc Type', _selectedDocType, _dynamicDocTypes, (val) { setState(() => _selectedDocType = val!); _applyFiltersAndSort(); }, w),`,
`              ]);`,
`            }),`,
`          ]),`,
`        ),`,
`        const SizedBox(height: CRMSpacing.m),`,
`        if (_filteredDocuments.isEmpty)`,
`          CRMEmptyState(title: 'No Provider Documents', description: 'No service agent records match the current filters.', actionLabel: 'Reset Filters', onActionPressed: _resetFilters)`,
`        else if (isMobile)`,
`          Column(children: [..._paginatedDocuments.map((doc) => _buildMobileDocumentCard(doc)), _buildMobilePagination()])`,
`        else`,
`          LayoutBuilder(builder: (ctx, cons) {`,
`            final sf = cons.maxWidth > 980 ? cons.maxWidth / 980 : 1.0;`,
`            return CRMDataTable<ServiceAgentDocument>(`,
`              currentPage: _currentPage, totalPages: _totalPages,`,
`              onPageChanged: (p) => setState(() => _currentPage = p),`,
`              totalItems: _filteredDocuments.length, itemsPerPage: _pageSize,`,
`              onItemsPerPageChanged: (r) { setState(() { _pageSize = r; _currentPage = 1; }); _applyFiltersAndSort(); },`,
`              sortField: _sortField, sortAscending: _sortAscending,`,
`              onSort: (f, asc) { setState(() { _sortField = f; _sortAscending = asc; }); _applyFiltersAndSort(); },`,
`              columns: [`,
`                CRMColumn<ServiceAgentDocument>(label: 'Agent Name', sortable: true, sortField: 'agentName', width: 140 * sf,`,
`                    cellBuilder: (doc) => Text(doc.agentName, style: CRMTypography.bodyMedium.copyWith(fontWeight: FontWeight.bold, color: CRMColors.textOf(context)))),`,
`                CRMColumn<ServiceAgentDocument>(label: 'Service Type', sortable: true, sortField: 'serviceType', width: 110 * sf,`,
`                    cellBuilder: (doc) => Text(doc.serviceType, style: TextStyle(color: CRMColors.textOf(context)))),`,
`                CRMColumn<ServiceAgentDocument>(label: 'Mobile Number', width: 110 * sf,`,
`                    cellBuilder: (doc) => Text(doc.mobileNumber, style: TextStyle(color: CRMColors.textOf(context)))),`,
`                CRMColumn<ServiceAgentDocument>(label: 'Document Type', sortable: true, sortField: 'documentType', width: 160 * sf,`,
`                    cellBuilder: (doc) => Row(children: [`,
`                      FileIconHelper.getIconForExtension(doc.fileExtension),`,
`                      const SizedBox(width: 8),`,
`                      Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [`,
`                        Text(doc.documentType, style: CRMTypography.bodyMedium.copyWith(fontWeight: FontWeight.w600, color: CRMColors.textOf(context)), maxLines: 1, overflow: TextOverflow.ellipsis),`,
`                        Text(doc.fileSize, style: CRMTypography.caption.copyWith(color: CRMColors.textSecondaryOf(context))),`,
`                        TextButton(`,
`                          onPressed: () async { final url = doc.fileUrl; if (url != null && url.isNotEmpty) { final uri = Uri.parse(url); if (await canLaunchUrl(uri)) await launchUrl(uri, mode: LaunchMode.externalApplication); } },`,
`                          style: TextButton.styleFrom(padding: EdgeInsets.zero, minimumSize: const Size(0, 0), tapTargetSize: MaterialTapTargetSize.shrinkWrap),`,
`                          child: Text('View', style: TextStyle(color: CRMColors.primaryOf(context), fontSize: 12, fontWeight: FontWeight.bold)),`,
`                        ),`,
`                      ])),`,
`                    ])),`,
`                CRMColumn<ServiceAgentDocument>(label: 'Upload Date', sortable: true, sortField: 'uploadDate', width: 100 * sf,`,
`                    cellBuilder: (doc) => Text(DateFormat('dd MMM yyyy').format(doc.uploadDate), style: TextStyle(color: CRMColors.textOf(context)))),`,
`                CRMColumn<ServiceAgentDocument>(label: 'Uploaded By', width: 100 * sf,`,
`                    cellBuilder: (doc) => Text(doc.uploadedBy, style: TextStyle(color: CRMColors.textOf(context)))),`,
`                CRMColumn<ServiceAgentDocument>(label: 'Actions', width: 60 * sf,`,
`                    cellBuilder: (doc) => PopupMenuButton<String>(`,
`                      icon: Icon(Icons.more_vert_rounded, color: CRMColors.textSecondaryOf(context)),`,
`                      onSelected: (val) { switch (val) { case 'view': _viewDocument(doc); break; case 'edit': _showUploadEditDialog(doc); break; case 'delete': _deleteDocument(doc); break; } },`,
`                      itemBuilder: (ctx) => [`,
`                        const PopupMenuItem(value: 'view', child: Row(children: [Icon(Icons.visibility_outlined, size: 18), SizedBox(width: 8), Text('View')])),`,
`                        const PopupMenuItem(value: 'edit', child: Row(children: [Icon(Icons.edit_outlined, size: 18), SizedBox(width: 8), Text('Edit')])),`,
`                        const PopupMenuDivider(),`,
`                        const PopupMenuItem(value: 'delete', child: Row(children: [Icon(Icons.delete_outline_rounded, color: CRMColors.danger, size: 18), SizedBox(width: 8), Text('Delete', style: TextStyle(color: CRMColors.danger))])),`,
`                      ],`,
`                    )),`,
`              ],`,
`              items: _paginatedDocuments,`,
`            );`,
`          }),`,
`      ]),`,
`    );`,
`  }`,
``,
`  Widget _buildFilterDropdown(String label, String currentValue, List<String> items, void Function(String?) onChanged, double width) {`,
`    return SizedBox(`,
`      width: width,`,
`      child: DropdownButtonFormField<String>(`,
`        value: currentValue, isExpanded: true,`,
`        dropdownColor: CRMColors.cardBgOf(context),`,
`        decoration: InputDecoration(`,
`          labelText: label, labelStyle: CRMTypography.caption.copyWith(color: CRMColors.textSecondaryOf(context)),`,
`          contentPadding: const EdgeInsets.symmetric(horizontal: CRMSpacing.m, vertical: 10),`,
`          filled: true, fillColor: CRMColors.backgroundOf(context),`,
`          border: OutlineInputBorder(borderRadius: BorderRadius.circular(CRMBorderRadius.s), borderSide: BorderSide(color: CRMColors.borderOf(context).withOpacity(0.6))),`,
`          enabledBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(CRMBorderRadius.s), borderSide: BorderSide(color: CRMColors.borderOf(context).withOpacity(0.6))),`,
`          focusedBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(CRMBorderRadius.s), borderSide: BorderSide(color: CRMColors.primaryOf(context), width: 1.5)),`,
`        ),`,
`        style: CRMTypography.body.copyWith(color: CRMColors.textOf(context), fontSize: 13),`,
`        items: items.map((item) => DropdownMenuItem(value: item, child: Text(item, style: TextStyle(fontSize: 13, color: CRMColors.textOf(context)), overflow: TextOverflow.ellipsis))).toList(),`,
`        onChanged: onChanged,`,
`      ),`,
`    );`,
`  }`,
``,
`  Widget _buildMobileDocumentCard(ServiceAgentDocument doc) {`,
`    return Padding(`,
`      padding: const EdgeInsets.only(bottom: CRMSpacing.m),`,
`      child: CRMCard(`,
`        padding: const EdgeInsets.all(CRMSpacing.m),`,
`        child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [`,
`          Row(crossAxisAlignment: CrossAxisAlignment.start, children: [`,
`            FileIconHelper.getIconForExtension(doc.fileExtension, size: 24),`,
`            const SizedBox(width: CRMSpacing.s),`,
`            Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [`,
`              Text(doc.documentType, style: CRMTypography.bodyMedium.copyWith(fontWeight: FontWeight.bold, color: CRMColors.textOf(context)), maxLines: 2, overflow: TextOverflow.ellipsis),`,
`              Text('\${doc.fileSize} • \${doc.agentName}', style: CRMTypography.caption.copyWith(color: CRMColors.textSecondaryOf(context))),`,
`            ])),`,
`            PopupMenuButton<String>(`,
`              icon: Icon(Icons.more_vert_rounded, color: CRMColors.textSecondaryOf(context)),`,
`              padding: EdgeInsets.zero, constraints: const BoxConstraints(),`,
`              onSelected: (val) { switch (val) { case 'view': _viewDocument(doc); break; case 'edit': _showUploadEditDialog(doc); break; case 'delete': _deleteDocument(doc); break; } },`,
`              itemBuilder: (ctx) => [`,
`                const PopupMenuItem(value: 'view', child: Row(children: [Icon(Icons.visibility_outlined, size: 18), SizedBox(width: 8), Text('View')])),`,
`                const PopupMenuItem(value: 'edit', child: Row(children: [Icon(Icons.edit_outlined, size: 18), SizedBox(width: 8), Text('Edit')])),`,
`                const PopupMenuDivider(),`,
`                const PopupMenuItem(value: 'delete', child: Row(children: [Icon(Icons.delete_outline_rounded, color: CRMColors.danger, size: 18), SizedBox(width: 8), Text('Delete', style: TextStyle(color: CRMColors.danger))])),`,
`              ],`,
`            ),`,
`          ]),`,
`          const SizedBox(height: CRMSpacing.m),`,
`          const Divider(height: 1),`,
`          const SizedBox(height: CRMSpacing.s),`,
`          _buildMobileDetailItem('Agent Name', doc.agentName),`,
`          _buildMobileDetailItem('Service Type', doc.serviceType),`,
`          _buildMobileDetailItem('Mobile Number', doc.mobileNumber),`,
`          _buildMobileDetailItem('Uploaded By', doc.uploadedBy),`,
`          _buildMobileDetailItem('Upload Date', DateFormat('dd MMM yyyy').format(doc.uploadDate)),`,
`          const SizedBox(height: CRMSpacing.m),`,
`          Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [`,
`            CRMStatusChip(status: doc.status.displayName),`,
`            Text(doc.fileExtension.toUpperCase(), style: CRMTypography.captionBold.copyWith(color: CRMColors.textMutedOf(context))),`,
`          ]),`,
`        ]),`,
`      ),`,
`    );`,
`  }`,
``,
`  Widget _buildMobileDetailItem(String label, String value) {`,
`    return Padding(`,
`      padding: const EdgeInsets.symmetric(vertical: 3.0),`,
`      child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [`,
`        Text(label, style: CRMTypography.caption.copyWith(color: CRMColors.textSecondaryOf(context))),`,
`        const SizedBox(width: CRMSpacing.m),`,
`        Expanded(child: Text(value, textAlign: TextAlign.end, style: CRMTypography.bodyMedium.copyWith(color: CRMColors.textOf(context), fontSize: 12.5, fontWeight: FontWeight.w500), overflow: TextOverflow.ellipsis)),`,
`      ]),`,
`    );`,
`  }`,
``,
`  Widget _buildMobilePagination() {`,
`    if (_totalPages <= 1) return const SizedBox.shrink();`,
`    return Padding(`,
`      padding: const EdgeInsets.only(top: CRMSpacing.s, bottom: CRMSpacing.l),`,
`      child: CRMCard(`,
`        padding: const EdgeInsets.symmetric(horizontal: CRMSpacing.m, vertical: CRMSpacing.xs),`,
`        child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [`,
`          Text('Page \\$_currentPage of \\$_totalPages', style: CRMTypography.captionBold.copyWith(color: CRMColors.textSecondaryOf(context))),`,
`          Row(children: [`,
`            IconButton(icon: const Icon(Icons.chevron_left_rounded), onPressed: _currentPage > 1 ? () => setState(() => _currentPage--) : null),`,
`            IconButton(icon: const Icon(Icons.chevron_right_rounded), onPressed: _currentPage < _totalPages ? () => setState(() => _currentPage++) : null),`,
`          ]),`,
`        ]),`,
`      ),`,
`    );`,
`  }`,
`}`,
``,
`String generateUuidV4() {`,
`  final random = Random.secure();`,
`  final hexDigits = '0123456789abcdef';`,
`  final charCodes = List<int>.generate(36, (index) {`,
`    if (index == 8 || index == 13 || index == 18 || index == 23) return 45;`,
`    if (index == 14) return 52;`,
`    final digit = random.nextInt(16);`,
`    if (index == 19) return hexDigits.codeUnitAt((digit & 0x3) | 0x8);`,
`    return hexDigits.codeUnitAt(digit);`,
`  });`,
`  return String.fromCharCodes(charCodes);`,
`}`,
];

fs.writeFileSync(target, L.join('\\n'), 'utf8');
console.log('File written.');
