const fs = require('fs');
const target = 'd:/NB PropKart/propertytech/lib/features/library/screens/service_agent_library_screen.dart';
const L = [];
L.push('');
L.push('  Future<void> _approveAgent(ServiceAgent agent) async {');
L.push('    try {');
L.push('      await Supabase.instance.client.from("service_agents").update({');
L.push('        "approval_status": "approved", "approved_by_name": _currentUserName,');
L.push('        "approved_at": DateTime.now().toUtc().toIso8601String(),');
L.push('      }).eq("id", agent.id);');
L.push('      await _loadAgents();');
L.push('      if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(');
L.push('        content: Text("${agent.agentName} approved!"), backgroundColor: CRMColors.success, behavior: SnackBarBehavior.floating));');
L.push('    } catch (e) { debugPrint("[ApproveAgent] $e"); }');
L.push('  }');
L.push('');
L.push('  Future<void> _rejectAgent(ServiceAgent agent) async {');
L.push('    final confirm = await CRMDialogs.showDeleteConfirmation(context,');
L.push('      title: "Reject Agent", content: "Reject agent ${agent.agentName}? They will be removed from pending.");');
L.push('    if (confirm != true) return;');
L.push('    try {');
L.push('      await Supabase.instance.client.from("service_agents").update({"approval_status": "rejected"}).eq("id", agent.id);');
L.push('      await _loadAgents();');
L.push('      if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(');
L.push('        content: Text("${agent.agentName} rejected."), backgroundColor: CRMColors.danger, behavior: SnackBarBehavior.floating));');
L.push('    } catch (e) { debugPrint("[RejectAgent] $e"); }');
L.push('  }');
L.push('');
L.push('  Future<void> _deleteAgent(ServiceAgent agent) async {');
L.push('    final confirm = await CRMDialogs.showDeleteConfirmation(context,');
L.push('      title: "Delete Agent", content: "Delete ${agent.agentName}? This cannot be undone.");');
L.push('    if (confirm != true) return;');
L.push('    try {');
L.push('      await Supabase.instance.client.from("service_agents").delete().eq("id", agent.id);');
L.push('      await _loadAgents();');
L.push('    } catch (e) { debugPrint("[DeleteAgent] $e"); }');
L.push('  }');
L.push('');
L.push('  void _viewDocument(ServiceAgentDocument doc) {');
L.push('    showDialog(context: context, builder: (context) => Dialog(');
L.push('      backgroundColor: CRMColors.surfaceElevatedOf(context),');
L.push('      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(CRMBorderRadius.dialog)),');
L.push('      child: ConstrainedBox(constraints: const BoxConstraints(maxWidth: 550),');
L.push('        child: Padding(padding: const EdgeInsets.all(CRMSpacing.l),');
L.push('          child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [');
L.push('            Row(children: [');
L.push('              FileIconHelper.getIconForExtension(doc.fileExtension, size: 28),');
L.push('              const SizedBox(width: CRMSpacing.s),');
L.push('              Expanded(child: Text(doc.documentName, style: CRMTypography.sectionTitle.copyWith(color: CRMColors.textOf(context)), maxLines: 1, overflow: TextOverflow.ellipsis)),');
L.push('              CRMStatusChip(status: doc.status.displayName),');
L.push('            ]),');
L.push('            const Divider(height: CRMSpacing.xl),');
L.push('            _buildDetailRow(context, "Agent Name:", doc.agentName),');
L.push('            _buildDetailRow(context, "Service Type:", doc.serviceType),');
L.push('            _buildDetailRow(context, "Mobile Number:", doc.mobileNumber),');
L.push('            _buildDetailRow(context, "Document Type:", doc.documentType),');
L.push('            _buildDetailRow(context, "Uploaded On:", DateFormat("dd MMM yyyy, hh:mm a").format(doc.uploadDate)),');
L.push('            _buildDetailRow(context, "Uploaded By:", doc.uploadedBy),');
L.push('            const SizedBox(height: CRMSpacing.l),');
L.push('            Row(mainAxisAlignment: MainAxisAlignment.end, children: [');
L.push('              CRMButton(label: "Close", variant: CRMButtonVariant.outline, onPressed: () => Navigator.pop(context)),');
L.push('              if (doc.fileUrl != null && doc.fileUrl!.startsWith("http")) ...[');
L.push('                const SizedBox(width: CRMSpacing.s),');
L.push('                CRMButton(label: "Open Document", variant: CRMButtonVariant.primary,');
L.push('                  prefixIcon: Icons.open_in_new_rounded,');
L.push('                  onPressed: () async {');
L.push('                    var openUrl = doc.fileUrl!;');
L.push('                    if (openUrl.contains("res.cloudinary.com") && openUrl.toLowerCase().contains(".pdf") && openUrl.contains("/upload/") && !openUrl.contains("/upload/f_")) {');
L.push('                      openUrl = openUrl.replaceFirst("/upload/", "/upload/f_jpg/");');
L.push('                    }');
L.push('                    final uri = Uri.parse(openUrl);');
L.push('                    if (await canLaunchUrl(uri)) await launchUrl(uri, mode: LaunchMode.externalApplication);');
L.push('                  }),');
L.push('              ],');
L.push('            ]),');
L.push('          ]),');
L.push('        ),');
L.push('      ),');
L.push('    ));');
L.push('  }');
L.push('');
L.push('  Widget _buildDetailRow(BuildContext context, String label, String value) {');
L.push('    return Padding(padding: const EdgeInsets.symmetric(vertical: 4.0),');
L.push('      child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [');
L.push('        SizedBox(width: 140, child: Text(label, style: CRMTypography.captionBold.copyWith(color: CRMColors.textSecondaryOf(context)))),');
L.push('        Expanded(child: Text(value, style: CRMTypography.bodyMedium.copyWith(color: CRMColors.textOf(context)))),');
L.push('      ]));');
L.push('  }');
L.push('');
L.push('  void _deleteDocument(ServiceAgentDocument doc) async {');
L.push('    final confirm = await CRMDialogs.showDeleteConfirmation(context,');
L.push('      title: "Delete Document", content: "Delete ${doc.documentName}? This cannot be undone.");');
L.push('    if (confirm != true) return;');
L.push('    try {');
L.push('      await Supabase.instance.client.from("service_agent_documents").delete().eq("id", doc.id);');
L.push('      setState(() { _allDocuments.removeWhere((d) => d.id == doc.id); _applyFiltersAndSort(); });');
L.push('      if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(');
L.push('        content: Text("${doc.documentName} deleted."), backgroundColor: CRMColors.danger, behavior: SnackBarBehavior.floating));');
L.push('    } catch (e) { debugPrint("Delete doc error: $e"); }');
L.push('  }');
fs.appendFileSync(target, L.join('\n'), 'utf8');
console.log('Part C OK');
