const fs = require('fs');
const target = 'd:/NB PropKart/propertytech/lib/features/library/screens/service_agent_library_screen.dart';
const L = [];
// Imports
L.push("import 'package:flutter/material.dart';");
L.push("import 'package:intl/intl.dart';");
L.push("import 'dart:math';");
L.push("import 'package:url_launcher/url_launcher.dart';");
L.push("import 'package:supabase_flutter/supabase_flutter.dart';");
L.push("import '../../../core/design_system/tokens/app_colors.dart';");
L.push("import '../../../core/design_system/tokens/app_spacing.dart';");
L.push("import '../../../core/design_system/tokens/app_typography.dart';");
L.push("import '../../../core/design_system/widgets/buttons.dart';");
L.push("import '../../../core/design_system/widgets/cards.dart';");
L.push("import '../../../core/design_system/widgets/crm_data_table.dart';");
L.push("import '../../../core/design_system/widgets/crm_status_chips.dart';");
L.push("import '../../../core/design_system/widgets/dialogs.dart';");
L.push("import '../../../core/design_system/widgets/empty_state.dart';");
L.push("import '../../../core/design_system/widgets/inputs.dart';");
L.push("import '../models/document_model.dart';");
L.push("import 'library_widgets.dart';");
L.push("import 'agent_widgets.dart';");
L.push("");
// Widget
L.push("class ServiceAgentLibraryScreen extends StatefulWidget {");
L.push("  const ServiceAgentLibraryScreen({super.key});");
L.push("  @override");
L.push("  State<ServiceAgentLibraryScreen> createState() => _ServiceAgentLibraryScreenState();");
L.push("}");
L.push("");
L.push("class _ServiceAgentLibraryScreenState extends State<ServiceAgentLibraryScreen>");
L.push("    with SingleTickerProviderStateMixin {");
L.push("  late TabController _tabController;");
L.push("  List<ServiceAgentDocument> _allDocuments = [];");
L.push("  List<ServiceAgentDocument> _filteredDocuments = [];");
L.push("  List<ServiceAgent> _approvedAgents = [];");
L.push("  List<ServiceAgent> _pendingAgents = [];");
L.push("  bool _agentsLoading = false;");
L.push("  String _currentUserRole = '';");
L.push("  String _currentUserName = '';");
L.push("  String? _currentUserId;");
L.push("  String? _sortField = 'uploadDate';");
L.push("  bool _sortAscending = false;");
L.push("  int _currentPage = 1;");
L.push("  int _pageSize = 10;");
L.push("  final TextEditingController _searchController = TextEditingController();");
L.push("  String _selectedServiceType = 'All';");
L.push("  String _selectedDocType = 'All';");
L.push("  bool _isLoading = false;");
L.push("");
L.push("  final List<String> _serviceTypes = [");
L.push("    'All', 'Electrician', 'Plumber', 'Carpenter', 'Painter',");
L.push("    'AC Technician', 'Cleaning Service', 'Pest Control', 'CCTV Service',");
L.push("    'Interior Designer', 'Movers & Packers', 'Other'");
L.push("  ];");
L.push("");
L.push("  List<String> get _dynamicDocTypes {");
L.push("    final types = _allDocuments.map((d) => d.documentType).toSet().toList();");
L.push("    if (!types.contains('Aadhaar Card')) types.insert(0, 'Aadhaar Card');");
L.push("    types.sort((a, b) { if (a == 'Aadhaar Card') return -1; if (b == 'Aadhaar Card') return 1; return a.compareTo(b); });");
L.push("    return ['All', ...types];");
L.push("  }");
L.push("");
L.push("  bool get _isAdmin => _currentUserRole == 'Admin' || _currentUserRole == 'Super Admin';");
L.push("");
L.push("  @override");
L.push("  void initState() {");
L.push("    super.initState();");
L.push("    _tabController = TabController(length: 3, vsync: this);");
L.push("    _fetchCurrentUser();");
L.push("    _loadDocumentsFromSupabase();");
L.push("    _loadAgents();");
L.push("  }");
L.push("");
L.push("  @override");
L.push("  void dispose() {");
L.push("    _tabController.dispose();");
L.push("    _searchController.dispose();");
L.push("    super.dispose();");
L.push("  }");
L.push("");
L.push("  Future<void> _fetchCurrentUser() async {");
L.push("    try {");
L.push("      final user = Supabase.instance.client.auth.currentUser;");
L.push("      if (user == null) return;");
L.push("      _currentUserId = user.id;");
L.push("      final profile = await Supabase.instance.client");
L.push("          .from('users').select('full_name, roles(name)').eq('id', user.id).maybeSingle();");
L.push("      if (profile != null && mounted) {");
L.push("        setState(() {");
L.push("          _currentUserRole = profile['roles']?['name']?.toString() ?? '';");
L.push("          _currentUserName = profile['full_name']?.toString() ?? user.email?.split('@').first ?? '';");
L.push("        });");
L.push("      }");
L.push("    } catch (e) { debugPrint('[SA] fetchCurrentUser error: \'); }");
L.push("  }");
L.push("");
L.push("  Future<void> _loadAgents() async {");
L.push("    if (mounted) setState(() => _agentsLoading = true);");
L.push("    try {");
L.push("      final response = await Supabase.instance.client");
L.push("          .from('service_agents').select().order('created_at', ascending: false);");
L.push("      final agents = (response as List).map((j) => ServiceAgent.fromJson(j as Map<String, dynamic>)).toList();");
L.push("      if (mounted) {");
L.push("        setState(() {");
L.push("          _approvedAgents = agents.where((a) => a.approvalStatus == ServiceAgentApprovalStatus.approved).toList();");
L.push("          _pendingAgents = agents.where((a) => a.approvalStatus == ServiceAgentApprovalStatus.pending).toList();");
L.push("        });");
L.push("      }");
L.push("    } catch (e) { debugPrint('[SA] loadAgents error: \'); }");
L.push("    finally { if (mounted) setState(() => _agentsLoading = false); }");
L.push("  }");
L.push("");
L.push("  Future<void> _loadDocumentsFromSupabase() async {");
L.push("    setState(() => _isLoading = true);");
L.push("    try {");
L.push("      final response = await Supabase.instance.client");
L.push("          .from('service_agent_documents').select().order('upload_date', ascending: false);");
L.push("      final docs = (response as List).map((json) => ServiceAgentDocument(");
L.push("        id: json['id']?.toString() ?? '',");
L.push("        agentName: json['agent_name']?.toString() ?? '',");
L.push("        serviceType: json['service_type']?.toString() ?? '',");
L.push("        mobileNumber: json['mobile_number']?.toString() ?? '',");
L.push("        documentName: json['document_type']?.toString() ?? '',");
L.push("        documentType: json['document_type']?.toString() ?? '',");
L.push("        uploadDate: DateTime.parse(json['upload_date']?.toString() ?? DateTime.now().toIso8601String()),");
L.push("        uploadedBy: json['uploaded_by']?.toString() ?? 'admin',");
L.push("        status: DocumentStatusExtension.fromString(json['status']?.toString() ?? 'active'),");
L.push("        description: json['description']?.toString() ?? '',");
L.push("        fileSize: json['file_size']?.toString() ?? '0 KB',");
L.push("        fileExtension: json['file_extension']?.toString() ?? 'pdf',");
L.push("        fileUrl: json['file_url']?.toString() ?? '',");
L.push("      )).toList();");
L.push("      setState(() { _allDocuments = docs; _applyFiltersAndSort(); });");
L.push("    } catch (e) { debugPrint('Error loading docs: \'); }");
L.push("    finally { if (mounted) setState(() => _isLoading = false); }");
L.push("  }");
L.push("");
L.push("  void _applyFiltersAndSort() {");
L.push("    List<ServiceAgentDocument> temp = List.from(_allDocuments);");
L.push("    final q = _searchController.text.trim().toLowerCase();");
L.push("    if (q.isNotEmpty) {");
L.push("      temp = temp.where((d) => d.agentName.toLowerCase().contains(q) || d.documentName.toLowerCase().contains(q) || d.documentType.toLowerCase().contains(q)).toList();");
L.push("    }");
L.push("    if (_selectedServiceType != 'All') temp = temp.where((d) => d.serviceType == _selectedServiceType).toList();");
L.push("    if (_selectedDocType != 'All') temp = temp.where((d) => d.documentType == _selectedDocType).toList();");
L.push("    if (_sortField != null) {");
L.push("      temp.sort((a, b) {");
L.push("        dynamic valA, valB;");
L.push("        switch (_sortField) {");
L.push("          case 'agentName': valA = a.agentName.toLowerCase(); valB = b.agentName.toLowerCase(); break;");
L.push("          case 'serviceType': valA = a.serviceType.toLowerCase(); valB = b.serviceType.toLowerCase(); break;");
L.push("          case 'uploadDate': valA = a.uploadDate; valB = b.uploadDate; break;");
L.push("          default: valA = a.uploadDate; valB = b.uploadDate;");
L.push("        }");
L.push("        int comp = valA.compareTo(valB);");
L.push("        return _sortAscending ? comp : -comp;");
L.push("      });");
L.push("    }");
L.push("    setState(() { _filteredDocuments = temp; _currentPage = 1; });");
L.push("  }");
L.push("");
L.push("  void _resetFilters() {");
L.push("    _searchController.clear();");
L.push("    setState(() { _selectedServiceType = 'All'; _selectedDocType = 'All'; });");
L.push("    _applyFiltersAndSort();");
L.push("  }");
L.push("");
L.push("  List<ServiceAgentDocument> get _paginatedDocuments {");
L.push("    int start = (_currentPage - 1) * _pageSize;");
L.push("    int end = (start + _pageSize).clamp(0, _filteredDocuments.length);");
L.push("    if (start >= _filteredDocuments.length) return [];");
L.push("    return _filteredDocuments.sublist(start, end);");
L.push("  }");
L.push("  int get _totalPages => (_filteredDocuments.length / _pageSize).ceil();");
fs.writeFileSync(target, L.join('\n'), 'utf8');
console.log('Part A OK, lines:', L.length);
